### PR TITLE
[revamp] Qt5 recipe

### PR DESCRIPTION
**Pull request by thopiekar**
Just added my work here, so it won't get lost for you.
Feedback is welcome of course.

Qt Bugs:
[https://bugreports.qt.io/browse/QTBUG-48134]

### CODE REVIEW

**Comment by inclement** [comment]
This looks good to me. One small thing, you can replace the env var stuff for the SDK dir etc with retrieving these values from self.ctx, which has ndk_dir, sdk_dir and android_api properties. These are initialised when toolchain.py is run, and it checks multiple environment variables and user arguments to find their values.

**Comment by inclement** [comment]
I noticed that you're using os.environ, but for a normal recipe you'd want to use self.get_recipe_env(arch.arch) to get the environment with everything set up for android arm compilation. But maybe this is deliberate because qt5 knows how to do it on its own?

**Comment by thopiekar** [comment]
Just added a automated detection of the available NDK. When just cherry-picking commit https://github.com/thopiekar/python-for-android_fork/commit/98ed343c28dd45df6fce2b33c87c3766cce49984 , it also needs https://github.com/thopiekar/python-for-android_fork/commit/f8c81929e567eb28e94c2ab593c2e309b545cee1 which I found after rebuilding everything.

**Comment by thopiekar** [comment]
@inclement Yes, following the Qt5 docs I have to use the default environment and tell ./configure where to find all tools. It doesn't need something like push_arm or pop_arm in the old p4a.

**Comment by inclement** [comment]
Okay, just checking.

**Comment by thopiekar** [comment]
See: https://wiki.qt.io/Qt5ForAndroidBuilding

**Comment by thopiekar** [comment]
Should be ready now. (Fingers crossed)

**Comment by dl1ksv** [comment]
I just tried your qt5 recipe. I get the following error:

[INFO]:    running configure -xplatform android-g++ -prefix /home/schroer/.local/share/python-for-android/build... (and 549 more)
           working ... Can not detect the android host. Please use -android-ndk-host option to specify one ...

The android host in the configure script is set to

 -android-ndk-host linux-Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz

I think it should be

linux-x86_64

**Comment by dl1ksv** [comment]
Setting android-ndk-host to linux-x86_64
compiling starts, but after some times it fails with:

running make -j5
           working ... make[1]: Verzeichnis „/home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/q ...Traceback (most recent call last):
  File "/home/schroer/p4a/usr/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.3', 'console_scripts', 'p4a')()
  File "/home/schroer/p4a/usr/lib/python/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 2428, in __init__
    getattr(self, args.command)(unknown)
  File "/home/schroer/p4a/usr/lib/python/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 169, in wrapper_func
    args = build_dist_from_args(ctx, dist, args)
  File "/home/schroer/p4a/usr/lib/python/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 2214, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/schroer/p4a/usr/lib/python/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 2029, in build_recipes
    recipe.build_arch(arch)
  File "/home/schroer/p4a/usr/lib/python/python_for_android-0.3-py2.7.egg/pythonforandroid/recipes/qt5/__init__.py", line 71, in build_arch
    shprint(make, '-j5', _env=env)
  File "/home/schroer/p4a/usr/lib/python/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 129, in shprint
    for line in output:
  File "/home/schroer/p4a/usr/lib/python/sh-1.11-py2.7.egg/sh.py", line 565, in next
    self.wait()
  File "/home/schroer/p4a/usr/lib/python/sh-1.11-py2.7.egg/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/schroer/p4a/usr/lib/python/sh-1.11-py2.7.egg/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2

Is there a way to get better error messages ?

Running the make command in the build directory I get the error:

( test -e Makefile.bundledjar || /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtbase/bin/qmake /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtconnectivity/src/android/bluetooth/bundledjar.pro -o Makefile.bundledjar ) && make -f Makefile.bundledjar 
make[5]: Verzeichnis „/home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtconnectivity/src/android/bluetooth“ wird betreten
javac -source 6 -target 6 -Xlint:unchecked -bootclasspath /opt/android-sdk-update-manager/platforms/android-16/android.jar -cp /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtconnectivity/src/android/bluetooth/src/:/opt/android-sdk-update-manager/platforms/android-16/android.jar -d .classes.bundled src/org/qtproject/qt5/android/bluetooth/QtBluetoothBroadcastReceiver.java src/org/qtproject/qt5/android/bluetooth/QtBluetoothSocketServer.java src/org/qtproject/qt5/android/bluetooth/QtBluetoothInputStreamThread.java src/org/qtproject/qt5/android/bluetooth/QtBluetoothLE.java
src/org/qtproject/qt5/android/bluetooth/QtBluetoothLE.java:39: error: cannot find symbol
import android.bluetooth.BluetoothGatt;
                        ^
  symbol:   class BluetoothGatt
  location: package android.bluetooth
src/org/qtproject/qt5/android/bluetooth/QtBluetoothLE.java:40: error: cannot find symbol
import android.bluetooth.BluetoothGattCallback;

and so on.

**Comment by dl1ksv** [comment]
With -skip qtconnectivity it compiles. But installation fails.
[INFO]:    running make -j5 install
           working ... make: *** [module-qtwebkit-install_subtargets] Fehler 2 ...      

Running make install in the build directory results in:

make[2]: Verzeichnis „/home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore“ wird betreten
( test -e Makefile.LLIntOffsetsExtractor || /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtbase/bin/qmake /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore/LLIntOffsetsExtractor.pro -o Makefile.LLIntOffsetsExtractor ) && make -f Makefile.LLIntOffsetsExtractor install
make[3]: Verzeichnis „/home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore“ wird betreten
mkdir: das Verzeichnis „/libs/armeabi/“ kann nicht angelegt werden: Keine Berechtigung

It seems that the installation directory is wrong.

**Comment by thopiekar** [comment]
First of all, thank you for testing the recipe and details.

* Install errors often happen after reconfiguring the build. Please try to "clean_dists" and "clean_builds", then retry.

* The recipe is at the moment in a early stage. The compiling error might be related to an too low Android API. I'm using the following environment variables here:
```
ANDROIDSDK=/home/thopiekar/.android-tools/android-sdk/
ANDROIDNDK=/home/thopiekar/.android-tools/android-ndk/
ANDROIDNDKVER=r10e
ANDROIDAPI=19
```

* Thank you for catching the x86_64 problem. I get these outputs from platform module:
```
>>> platform.processor()
'x86_64'
>>> platform.machine()
'x86_64'
```

But platform.processor() returns a different string for you. Will fix that soon!

PS: Please use "```" at every beginning and end of an output. Editing old comments with that would be great ;)

**Comment by dl1ksv** [comment]
My settings are
```
ANDROIDNDKVER=r10d
ANDROIDAPI=16
>>> platform.processor()
'Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz'
>>> platform.machine()
'x86_64'

```
It builds and installs without errors with
```
'-android-ndk-host',          'linux-x86_64',
'-skip',                      'qtconnectivity',
'-skip',                      'qtwebkit',
```

**Comment by thopiekar** [comment]
The reason could be ANDROIDAPI=16.. I read somewhere that some components of qt5 depend on a minimum API version. There is no internal test on that when running ./configure so the build simply fails. Upgrade the API to 19 and try again if you need these components!

```
' Android API level 11 is required to build QtMultimedia. ' Android API level 18 is required to build QtBluetooth (from Qt 5.5 onwards). ' Android API level 11 and 16 are required for QtBase. ' Note that this is only necessary for building Qt itself. You can build Qt applications against any API level you wish, As long as it is equal to or higher than 13.
```
[https://wiki.qt.io/Qt5ForAndroidBuilding]

**Comment by thopiekar** [comment]
Fixed the problem above by adding an API check. It will disable components by Android API automaticly.

@dl1ksv: API's 19 until 14 are tested and working. API 20 doesn't work as it is a Android Wear API I guess. However, could you please try to build for API 21 if it is already supported by NDK r10d? Here on r10e it doesn't work.

**Comment by dl1ksv** [comment]
I checked the updated recipe with API version 16.
Compilation ends up successfully but installation still fails.

```[
INFO]:    Android API is lower than 18!
[WARNING]: * therefore QtConnectivity will be disabled...
[INFO]:    running configure -xplatform android-g++ -prefix /home/schroer/.local/share/python-for-android/build... (and 535 more)
           working ...  ...                                                                                        t5/armea ...
[INFO]:    running make -j9
           working ... make[1]: Verzeichnis „/home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/q ...
[INFO]:    running make -j9 install
           working ... make: *** [module-qtwebkit-install_subtargets] Fehler 2 ... 
 ```
Normally during installation an install prefix is used like

 ```
install -m 644 -p /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebchannel/src/imports/webchannel/plugins.qmltypes /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qt5-install/qml/QtWebChannel/

 ```
But at this point the prefix is probably missing.
 ```
make[2]: Verzeichnis „/home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore“ wird betreten
( test -e Makefile.LLIntOffsetsExtractor || /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtbase/bin/qmake /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore/LLIntOffsetsExtractor.pro -o Makefile.LLIntOffsetsExtractor ) && make -f Makefile.LLIntOffsetsExtractor install
make[3]: Verzeichnis „/home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore“ wird betreten
mkdir: das Verzeichnis „/libs/armeabi/“ kann nicht angelegt werden: Keine Berechtigung
Makefile.LLIntOffsetsExtractor:685: die Regel für Ziel „install_target“ scheiterte
make[3]: *** [install_target] Fehler 1
 ```
I have no idea why install tries to install to 
/libs

Of course skipping webkit will help.

I'll go to check API 19 and afterwards API 21

**Comment by thopiekar** [comment]
The installation issue really does not make any sense :disappointed: 
I experience this problem on other components which I collected here:
```
            skip_bug_install = ('-skip',                      'qt3d',              # Causes an install problem
                                '-skip',                      'qtcanvas3d',        # Causes an install problem
                                )
```
[https://github.com/thopiekar/python-for-android_fork/commit/87314b5404a3d541909002f4ce93e68009ca3b70#diff-1c0f5e98b27739d2ab8bab79529deec6R20]

If you like you can try to comment them out and see wheather it works for you or not. Would be great to find the reason or at least good details. I really think about adding a bug report on Qt's bugtracker about that. At least they should add the API check on their own. During ./configure all information is passed, so ./configure should be able to do it on it's own!

**Comment by dl1ksv** [comment]
Just tested API 19 and I get the same error. 

```
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (10, 11, 16, 18, 19, 21, 22)
[INFO]:    Requested API target 19 is available, continuing.

Result:
mkdir: das Verzeichnis „/libs/armeabi/“ kann nicht angelegt werden: Keine Berechtigung

```
I'm wondering that you don't get this problem.
I think this is not an API version problem, but a qt problem.

As I don't need webkit , I'll skip it and go further checking API 21

**Comment by thopiekar** [comment]
@dl1ksv Thank for making more tests! Yes, the source is the same. I hope they will clean up their Makefiles in the next release...
However, I just added more options, which will enable 3rd party libraries released with the qt5 code. The build is now taking much longer, as libjpeg, libpng and others were not used for the build. Additionally all qt components aka modules were probably not enabled before, as these libraries were missing.

**Comment by thopiekar** [comment]
Btw. now I also get:
```
make[3]: Entering directory '/home/thopiekar/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore'
[DEBUG]:        mkdir: das Verzeichnis »/libs“ kann nicht angelegt werden: Keine Berechtigung
[DEBUG]:        Makefile.LLIntOffsetsExtractor:711: recipe for target 'install_target' failed
[DEBUG]:        make[3]: *** [install_target] Error 1
[DEBUG]:        make[3]: Leaving directory '/home/thopiekar/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore'
[DEBUG]:        Makefile.JavaScriptCore:58: recipe for target 'sub-LLIntOffsetsExtractor-pro-install_subtargets-ordered' failed
[DEBUG]:        make[2]: *** [sub-LLIntOffsetsExtractor-pro-install_subtargets-ordered] Error 2
[DEBUG]:        make[2]: Leaving directory '/home/thopiekar/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit/Source/JavaScriptCore'
[DEBUG]:        Makefile:117: recipe for target 'sub-Source-JavaScriptCore-JavaScriptCore-pro-install_subtargets-ordered' failed
[DEBUG]:        make[1]: *** [sub-Source-JavaScriptCore-JavaScriptCore-pro-install_subtargets-ordered] Error 2
[DEBUG]:        make[1]: Leaving directory '/home/thopiekar/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtwebkit'
[DEBUG]:        Makefile:494: recipe for target 'module-qtwebkit-install_subtargets' failed
[DEBUG]:        make: *** [module-qtwebkit-install_subtargets] Error 2
```

**Comment by dl1ksv** [comment]
I see a small difference. In my case the directory that fails is 
/libs/armeabi/
and in your case it is
/libs
I think this is a failure in the qt configure process.

Meanwhile I tried API 21 and I got a very strange result:
Compiling fails with

```
cd 3rdparty/harfbuzz-ng/ && ( test -e Makefile || /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtbase/bin/qmake /home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtbase/src/3rdparty/harfbuzz-ng/harfbuzz-ng.pro -o Makefile ) && make -f Makefile 
make[3]: Verzeichnis „/home/schroer/.local/share/python-for-android/build/other_builds/qt5/armeabi/qt5/qtbase/src/3rdparty/harfbuzz-ng“ wird betreten
compiling src/hb-blob.cc
In file included from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/random:38:0,
                 from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algo.h:66,
                 from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/algorithm:62,
                 from ../../../include/QtCore/../../src/corelib/global/qglobal.h:85,
                 from ../../../include/QtCore/qglobal.h:1,
                 from ../../../include/QtCore/../../src/corelib/thread/qatomic.h:34,
                 from ../../../include/QtCore/qatomic.h:1,
                 from src/hb-atomic-private.hh:45,
                 from src/hb-object-private.hh:37,
                 from src/hb-blob.cc:34:
/opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cmath: In function 'constexpr int std::fpclassify(float)':
/opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cmath:562:33: error: 'FP_NAN' was not declared in this scope
   { return __builtin_fpclassify(FP_NAN, FP_INFINITE, FP_NORMAL,
```

 I reverted back to API 16 and it builds fine, if qtwebkit is skiped.

Maybe som compiler option is missing.

**Comment by thopiekar** [comment]
Thats really strange :disappointed:

**Comment by thopiekar** [comment]
Now depends on https://github.com/kivy/python-for-android/pull/443 :facepunch:

**Comment by dl1ksv** [comment]
FP_NAN and other constants are defined in math.h
This file exits for the different API versions. As I don't understand why this file is included for API <= 19 but not for API I copied the definitions into cmath.

Then qt5 compiles for API 21 ( still qtwebkit disabled)

**Comment by thopiekar** [comment]
Well, it looks like there is the difference between r10d and r10e. My NDK owns it:
```
thopiekar@home:~/.android-tools/android-ndk$ find . | grep "/math.h"
./platforms/android-15/arch-x86/usr/include/math.h
./platforms/android-15/arch-arm/usr/include/math.h
./platforms/android-15/arch-mips/usr/include/math.h
./platforms/android-21/arch-x86/usr/include/math.h
./platforms/android-21/arch-x86_64/usr/include/math.h
./platforms/android-21/arch-arm64/usr/include/math.h
./platforms/android-21/arch-arm/usr/include/math.h
./platforms/android-21/arch-mips64/usr/include/math.h
./platforms/android-21/arch-mips/usr/include/math.h
./platforms/android-19/arch-x86/usr/include/math.h
./platforms/android-19/arch-arm/usr/include/math.h
./platforms/android-19/arch-mips/usr/include/math.h
./platforms/android-8/arch-arm/usr/include/math.h
./platforms/android-13/arch-x86/usr/include/math.h
./platforms/android-13/arch-arm/usr/include/math.h
./platforms/android-13/arch-mips/usr/include/math.h
./platforms/android-4/arch-arm/usr/include/math.h
./platforms/android-12/arch-x86/usr/include/math.h
./platforms/android-12/arch-arm/usr/include/math.h
./platforms/android-12/arch-mips/usr/include/math.h
./platforms/android-17/arch-x86/usr/include/math.h
./platforms/android-17/arch-arm/usr/include/math.h
./platforms/android-17/arch-mips/usr/include/math.h
./platforms/android-9/arch-x86/usr/include/math.h
./platforms/android-9/arch-arm/usr/include/math.h
./platforms/android-9/arch-mips/usr/include/math.h
./platforms/android-14/arch-x86/usr/include/math.h
./platforms/android-14/arch-arm/usr/include/math.h
./platforms/android-14/arch-mips/usr/include/math.h
./platforms/android-5/arch-arm/usr/include/math.h
./platforms/android-3/arch-arm/usr/include/math.h
./platforms/android-16/arch-x86/usr/include/math.h
./platforms/android-16/arch-arm/usr/include/math.h
./platforms/android-16/arch-mips/usr/include/math.h
./platforms/android-18/arch-x86/usr/include/math.h
./platforms/android-18/arch-arm/usr/include/math.h
./platforms/android-18/arch-mips/usr/include/math.h
./tests/build/target-c-includes/jni/include/math.h
./tests/device/test-stlport/unit/math_header_test.c
./tests/device/test-gnustl-full/unit/math_header_test.c
./sources/cxx-stl/llvm-libc++/libcxx/test/depr/depr.c.headers/math_h.pass.cpp
./sources/cxx-stl/stlport/stlport/math.h
./sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/math.h
./sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/math.h
./sources/android/support/include/math.h
```

**Comment by dl1ksv** [comment]
That was a misunderstanding.r10d owns it, too. But it is not included and I don't understand why.
The difference between API 21 and API < 21 semms to be the use of pragma in the header files.

**Comment by thopiekar** [comment]
Ahh, OK, I thought the header file was missing for you.
However, I reported our installation problems at Qt's bugtracker and just got notified that they confirmed this bug. Hope they will fix that soon.

**Comment by inclement** [comment]
This got closed because I deleted the revamp branch - I wanted to find out which PRs were to it, but didn't mean that they should disappear. If you'd like to continue it, could you retarget on master, or if it's ready to merge (I wasn't sure about this) I can do that manually.

**Pull request closed without merging**
