### PR TITLE
Fixes App Icon and Presplash_Screen For Webview bootstrap

### PR DESCRIPTION
**Pull request by kengoon**
fix for #2552 and presplash_color not updating for webview bootstrap

### CODE REVIEW

**Review by misl6 — CHANGES_REQUESTED** [review]
Can you please rebase on develop and squash your commits into one?

**Comment by kengoon** [comment]
done, that.

**Comment by misl6** [comment]
I think that something gone wrong when you squashed into one commit.
No worries, I will squash it into one while merging.

For the next time: https://www.internalpointers.com/post/squash-commits-into-one-git

**Review by misl6 — APPROVED** [review]
Will squash into one commit while merging.

**Pull request merged**
