### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by Lookitup**
No metadata I hope -:)
image

### CODE REVIEW

**Comment by Lookitup** [comment]
And so my friends it's possible

**Comment by dessant** [comment]
@Lookitup, are you wearing swimming goggles right now?

**Comment by Lookitup** [comment]
Well ... Like no -:)

**Comment by Lookitup** [comment]
{\rtf1\ansi\ansicpg1252
{\fonttbl\f0\fnil\fcharset0 .HelveticaNeueInterface-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs34 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 }

**Comment by Lookitup** [comment]
Uh ur like a little stuck here (:-

 http://jack869.igenapps.com/windows-x

**Pull request closed without merging**
