### PR TITLE
Remove superfluous recipes

### PR DESCRIPTION
**Pull request by rnixx**
#1387

### CODE REVIEW

**Comment by AndreMiras** [comment]
Thank you @rnixx less is more, I love it!
Do you know why quite some tests are failing? https://travis-ci.org/kivy/python-for-android/jobs/585146437

**Comment by rnixx** [comment]
Seems that some of those recipes are tested. need to take a look

**Comment by AndreMiras** [comment]
Thank you to look into it :beers:
Once you're done with it, basically we just need to double check all the recipe we killed still import OK at runtime on device. I will verify that once CI is happy.

**Comment by rnixx** [comment]
@AndreMiras I re-added pysdl2 and six recipes because they showed up somewhere in tests in the dependencies list. Now CI is sane again. I had no closer look at the test implementation itself, an isolated look right now not makes much sense to me with #1745 and #1625 in mind. Once i find some more time, I'm interested in taking a closer look into dependency resolving, there's some room for improvement.

**Comment by AndreMiras** [comment]
Awesome work @rnixx thanks a mil, PR that remove code are my favorite ones!
This is definitely next in my list to test, hopefully before Wednesday.

**Comment by AndreMiras** [comment]
Hi @rnixx I started taking a look, but I get compilation errors (libffi) and I'm not able to perform my runtime tests. I'm not really sure why since the CI is fine :thinking: 
Can you rebase that pull request on `develop`?
```
git rebase upstream/develop
```
That would also kick theses merge commits we have and keep the history clean.

**Pull request closed without merging**
