### PR TITLE
Get --add-source working for dirs in Gradle builds

### PR DESCRIPTION
**Pull request by kollivier**
I had trouble making the file patterns work using `include` (no errors, but files didn't get included). However, this approach works for specifying source directories, which was our use case. Figured I'd post what we have now and see if anyone knows how to fix the patterns case, or knows if that case is used often?

### CODE REVIEW

**Comment by inclement** [comment]
I've previously tried this and had the same problems with getting patterns working, although I never tried the case without them so it's great to see that works.

Would you mind adding a warning during the templating, notifying the user that their pattern will be ignored (if they passed one)? But other than that, I'm very happy to merge.

**Comment by kollivier** [comment]
Good call, thanks! Just added a warning, would this work?

**Comment by inclement** [comment]
@kollivier Looks good, fixed a couple of typos, will merge when the tests pass.

**Comment by inclement** [comment]
Thanks again!

**Pull request merged**
