### PR TITLE
Ethereum related recipes

### PR DESCRIPTION
**Pull request by AndreMiras**
* ethash
  * libsecp256k1
  * pycryptodome
  * pyethereum
  * pysha3
  * scrypt
  * secp256k1
See https://github.com/ethereum

### CODE REVIEW

**Comment by AndreMiras** [comment]
Hi there, I'm currently working on a [Ethereum wallet](https://github.com/AndreMiras/PyWallet) application built on top of Kivy.
I had to create some custom recipes and I thought I could share.

**Comment by AndreMiras** [comment]
Thank you for such a quick feedback.
I'll try to add the versions for Pycryptodome and Pyethereum and see if it works fine.

**Comment by AndreMiras** [comment]
@KeyWeeUsr, I've updated the PR with version string for pycryptodome, pyethereum and pysha3.

**Comment by KeyWeeUsr** [comment]
@AndreMiras Nice, thanks for the contribution :)

**Pull request merged**
