### PR TITLE
fix bug preventing pure python dependencies to be installed under pyt…

### PR DESCRIPTION
**Pull request by loulouxiv**
…hon3

### CODE REVIEW

**Comment by loulouxiv** [comment]
I did not mean to add the second commit to the pull request. Please note that while the java modification compiles, I am not 100% sure that it does what the previous code meant.

**Comment by inclement** [comment]
Nice catch, thanks for the PR. I'd rather not merge these unrelated changes with it, but I'll just cherry-pick the first commit if you don't mind.

**Comment by loulouxiv** [comment]
No I don't mind, I will simply add these to another PR

**Comment by inclement** [comment]
Thanks, I've merged just the fix commit.

**Pull request closed without merging**
