### PR TITLE
Removes java concurrency/ folder

### PR DESCRIPTION
**Pull request by AndreMiras**
None of the class seems to be used.

### CODE REVIEW

**Comment by inclement** [comment]
Is there any chance there's pyjnius code using this?

**Comment by AndreMiras** [comment]
I haven't think about that one, I'll look into it, thanks

**Comment by AndreMiras** [comment]
It got introduced in https://github.com/kivy/python-for-android/pull/578 but I still don't have it clear why :smile:

**Comment by AndreMiras** [comment]
yes agree, if it breaks something someone should complain. Isn't it how software development works? :smile:

**Pull request merged**
