### PR TITLE
minimal bootstrap for PythonService

### PR DESCRIPTION
**Pull request by brussee**
Meant to be used with export_dist to just run a Python service from a normal Android app.

### CODE REVIEW

**Comment by brussee** [comment]
It does what I would like it to do.

I've also added a clean_bootstraps command to p4a toolchain.py

**Comment by inclement** [comment]
Nice. Would you be able to include my additions to the jni/src folder in the webview bootstrap to enable pyjnius to work with this bootstrap (plus some appropriate patch in the pyjnius recipe)? I think you just need to copy pyjniusjni.c and add it to the Android.mk.

I don't see a recipe calling ndk-build to actually build the start.c. Am I missing something here, or you would call it separately once the dist is exported (I'd have thought this wouldn't work due to path problems)?

**Comment by brussee** [comment]
The gradle build implicitly builds all .c files in the jni folder.

Some documentation about how to import the build files from the dist into a Android Gradle project is needed I think.
If I have time I will add that and also take a look at the pyjniusjni.c

Thanks for merging all my PR's!

**Comment by brussee** [comment]
I rebased on ac25fabfeb42d2d9a879bb2f55420d0827b6a8b9 and added pyjniusjni.c but have not tested it.

**Comment by inclement** [comment]
pyjnius will need a patch modification to work with this (currently it checks for the webviewjni recipe, but in retrospect this was a bad name and it should be something generic for all these bootstraps). If I merge this and make a couple of changes to that end, would you be able to test pyjnius in a trivial example (just import and autoclass)?

(Other than that, sorry for the delay, am I right in understanding that this is working well for you?)

**Comment by brussee** [comment]
Sorry for the delay. In the next couple of weeks I will be working on documentation.
Indeed it is working well for me for a while now.
I might (limited time) be able to test pyjnius after you merge the rename / refactor the webview components.

**Comment by brussee** [comment]
I've just confirmed pyjnius to work from the Python service with this script:
```
        from jnius import autoclass
        autoclass('java.lang.System').out.println('Hello world')

        Stack = autoclass('java.util.Stack')
        stack = Stack()
        stack.push('hello')
        stack.push('world')
        print stack.pop()
        print stack.pop()
```

06-22 01:05:22.907 5503-5582/org.tribler.android:service_Triblerd I/System.out: Hello world
06-22 01:05:22.940 5503-5582/org.tribler.android:service_Triblerd I/Triblerd: world
06-22 01:05:22.940 5503-5582/org.tribler.android:service_Triblerd I/Triblerd: hello

**Comment by brussee** [comment]
Ready to merge! :D

**Comment by inclement** [comment]
Great, thanks!

I changed 'clean_bootstraps' to 'clean_bootstrap_builds' for consistency. It would also be great if you could add a little doc about the purpose of this bootstrap, but there didn't seem to be a need to let it hold up merging the bulk of it.

**Pull request merged**
