### PR TITLE
Pygame sdl2

### PR DESCRIPTION
**Pull request by frankgould**
This is my first pull request. This attached recipe is generating the attached error.
[__init__.py.txt](https://github.com/kivy/python-for-android/files/870289/__init__.py.txt)
[error-25Marchat1.22.txt](https://github.com/kivy/python-for-android/files/870290/error-25Marchat1.22.txt)

### CODE REVIEW

**Comment by frankgould** [comment]
Is there anything else I need to provide for this pull request?

**Comment by frankgould** [comment]
Any idea when someone might be able to help with this? I hope I haven't offended anyone.

**Comment by KeyWeeUsr** [comment]
Well, unless the recipe is working (which I presume it isn't as you've mentioned some error), you'll either need to fix the error, or wait for someone to fix it. Such things mostly happen at the edges of the week i.e. Friday - Monday. However, don't take it like a real schedule, only as an [observation](https://github.com/kivy/python-for-android/graphs/punch-card).

Anyway, of what I see:

* liblink path is `None`
* `UserWarning: Unknown distribution option: 'zip_safe'` this seems like something internal, though I wonder [**where?!**](https://github.com/kivy/python-for-android/search?utf8=%E2%9C%93&q=zip_safe&type=)

I think recipes are installed together with p4a, therefore you'll need to edit it either in the installed folder (try `which p4a`), or include a new recipes folder (there's a switch mentioned in the documentation), or install p4a through `pip install -e <local clone folder>`.

**Comment by frankgould** [comment]
Thanks KeyWeeUsr. I'll have to wait for someone because this is way over my head. I can also plan to work with this someone to test to make sure we make it work for others.

**Comment by frankgould** [comment]
Update:  I was finally able to get opencv to work and do not need pygame_sdl2.  However, I am willing to work with someone to get this to work.  Please let me know and I will offer my time to solve this problem.  Until then, I'm moving forward.

**Comment by akshayaurora** [comment]
Please re-open when you get this in a shape to be merged.

**Pull request closed without merging**
