### PR TITLE
Support ruamel.yaml, improved yaml lib.

### PR DESCRIPTION
**Pull request by mixmastamyk**
Details at:  https://pypi.python.org/pypi/ruamel.yaml

Bug necessitating patch: 
https://bitbucket.org/ruamel/yaml/issues/114/

### CODE REVIEW

**Comment by inclement** [comment]
It looks like this issue was resolved in ruamel.yaml, would it be better now to just set the env var that seems to have been added?

**Comment by mixmastamyk** [comment]
Yes in general, however at the time I was using this, the fix had not made it to the release version on PyPI.  

Looks like it probably has by now.  I'm working on backend stuff now, but hope to get back to the kivy client in a week or two, and will take a look at a newer version of a ruamel.yaml  that does not need a patch.

**Comment by inclement** [comment]
Okay, sorry about the delay merging this, if this hasn't made it to pypi yet just let me know and I'll merge this version.

**Comment by AndreMiras** [comment]
I gave it a try and as in last pypi version `ruamel.yaml==0.15.77` the problem is still there.
I made a couple of fixes to the recipe and will merge if Travis is happy.

**Comment by AndreMiras** [comment]
Conditional build is green, even though I'm not too sure why it decided to fallback to python2. Because to me all the dependencies set is also compatible with `python3crystax`, here is the relevant part of the log:
```
[INFO]:    Found 4 acceptable bootstraps: ['webview', 'service_only', 'sdl2', 'pygame']
[INFO]:    Using the first of these: webview
[INFO]:    Found a single valid recipe set: ['hostpython2', 'python2', 'setuptools', u'ruamel.yaml']
[INFO]:    -> directory context testapps/
('recipes modified:', set([u'ruamel.yaml']))
('recipes to build:', set([u'ruamel.yaml']))
incompatible with python3crystax
falling back to python2
('recipes to build (no broken):', set([u'ruamel.yaml']))
('requirements:', u'ruamel.yaml,python2')
```
More details: https://api.travis-ci.org/v3/job/453630101/log.txt

**Pull request merged**
