### PR TITLE
This is a recipe for Icecream

### PR DESCRIPTION
**Pull request by Arjun-Somvanshi**
Hey, This is a recipe for Icecream, would really help buildozer give a colored output, let me know if something else is needed. Thanks.

### CODE REVIEW

**Comment by Arjun-Somvanshi** [comment]
hmm, any idea why it failed/?

**Comment by Arjun-Somvanshi** [comment]
Ah! that seemed to work.

**Comment by inclement** [comment]
This looks like a pure python module, does it actually need a recipe?

**Comment by Arjun-Somvanshi** [comment]
> This looks like a pure python module, does it actually need a recipe?

It's better to have a recipe than including the repository in every project I want to Icecream. It increases the size of the apk too.

**Comment by Arjun-Somvanshi** [comment]
[](https://github.com/mk-fg/pretty-yaml) pyaml seems to have a recipe though it's pure python. I think all external packages should be recipes instead of having users to include them in their projects, it not only will bloat the app, but makes the process of adding packages to your app more complex?

**Comment by Kulothungan16** [comment]
Maybe you should take a look at this tshirman's message about this module https://discord.com/channels/423249981340778496/678695971164520523/843264213425324042

**Comment by Arjun-Somvanshi** [comment]
> Maybe you should take a look at this @tshirtman's message about this module https://discord.com/channels/423249981340778496/678695971164520523/843264213425324042

Yes, as a part of this same thread it is suggested that either one has to clone this repo, and fix the bug as to why it doesn't compile to android or as Turtle suggested making a recipe for it should also solve the problem, and that is what I decided to do.

**Comment by inclement** [comment]
> Yes, as a part of this same thread it is suggested that either one has to clone this repo, and fix the bug as to why it doesn't compile to android and use that in buildozer.spec or as Turtle suggested making a recipe for it should also solve the problem, and that is what I decided to do.

That's fine, but you didn't state this in the first place, it isn't obvious that icecream is broken and needs a trivial recipe to fix an issue with its build.

> pyaml seems to have a recipe though it's pure python. I think all external packages should be recipes instead of having users to include them in their projects,

You don't in general need to include modules manually if they don't have recipes. It sounds like even if icecream has a bug that is fixed by using a recipe, you have a misconception about this.

**Comment by Arjun-Somvanshi** [comment]
Yes, I understand now what you mean now, I have had issues with a few other pure python packages too so this was a misconception. 
Is this pull request needing anything else? Would like someone to review it, if they have the time. :)

**Comment by tshirtman** [comment]
Wouldn’t this recipe need a patch to be actually helpful? But wouldn’t it be better to actually do a pull request on icecream solving the issue, (using the change i suggested in the linked discord thread), so it would benefit not just p4a/buildozer users, but any user of the project that would hit this bug?

**Pull request closed without merging**
