### PR TITLE
Made p4a call `sdkmanager` instead of `android` in new Android SDK versions

### PR DESCRIPTION
**Pull request by inclement**

### CODE REVIEW

**Comment by nocarryr** [comment]
In working through the same errors as in #1050 I've found that my android-sdk layout places `avdmanager` under `./tools/bin/avdmanager` instead of `./bin/avdmanager` (as shown in L232-L233).

I also have a depreciated version of the `./tools/android` callable, so in testing I had to move the `avdmanager` check to the top of the stack.

Not sure if this is what everyone is experiencing or not, but this is on a freshly installed VM (16.04) and fresh download of the sdk

**Comment by inclement** [comment]
@nocarryr Yeah, this PR is not quite right as I downloaded the SDK from scratch and misunderstood the directory structure. I have an improved version that isn't pushed yet.

**Comment by nocarryr** [comment]
@inclement :+1:  Thanks, just thought I'd share the discovery.  Have you also noticed any issues with a non-existent `build.xml` expected under `./tools/ant/` (within the sdk root)?

This may be a separate issue, but I thought I'd ask here in case you've come across it

**Comment by inclement** [comment]
@nocarryr Thanks for reporting it, it's always useful!

The build.xml problem is because the build tools no longer ship with ant, it is also deprecated. I think you can install an older version for now, or tito has done the work to make p4a use gradle instead (PR at https://github.com/kivy/python-for-android/pull/1042), which we're working to review and merge.

**Comment by nocarryr** [comment]
Thanks for the info, I haven't checked in on p4a progress in awhile so I'm​ catching up. Great work btw

**Pull request closed without merging**
