### PR TITLE
recipes: add new `uvloop` recipe

### LINKED ISSUE #2997: please add uvloop to recipes!
please add uvloop to recipes! uvloop is a fast, drop-in replacement of the built-in 'asyncio' event loop. This has greatly improved the performance of our project. We urgently need it.  please! 🙏🙏🙏
uvloop url: https://github.com/MagicStack/uvloop/tree/master

### PR DESCRIPTION
**Pull request by T-Dynamos**
Closes #2997

### CODE REVIEW

**Comment by T-Dynamos** [comment]
This PR was ready to be merged.

**Comment by misl6** [comment]
Do you need to make any changes / rebase as #3007 has been merged?

**Comment by T-Dynamos** [comment]
Surpassed by #3014

**Comment by vabt-igd** [comment]
@T-Dynamos Was this recipe working on p4a v2024.01.21?
When I use this pr on v2024.01.21, I get the following error message: `RuntimeError: the libuv submodule has not been checked out; try running “git submodule init; git submodule update”`. 
Converting to a CythonRecipe (as uvloop needs cython anyways) takes it a step further, but still results in `uvloop/request.pyx:64:21: undeclared name not builtin: convert_error`. 
Was there more work required to properly build uvloop for arm64-v8a on android?

**Pull request closed without merging**
