### PR TITLE
refactoring code with For Else

### PR DESCRIPTION
**Pull request by zjzh**
refactoring code with For Else which is more pythonic, concise and efficient; how do you think this change which has practical value？

### CODE REVIEW

**Review by tshirtman — APPROVED** [review]

**Comment by tshirtman** [comment]
While i think refactoring should be incidental, when needed, rather than for the sake of it, (or else we end up refactoring needlessly), this is indeed more natural, so i'm fine with it. :)

**Review by AndreMiras — APPROVED** [review]

**Comment by misl6** [comment]
Ouch! That was merged into `master` instead of `develop`.

**Comment by AndreMiras** [comment]
Ouch I missed that too :facepalm:  thanks for the heads up.
I imagine we could cherry pick back to develop to have them align for next release.
Or we could simply revert it or do we have other idea?

**Comment by misl6** [comment]
It's a really minor cosmetic change, so doesn't really change anything for users that are targeting `master`.
As we did in past I think is great to cherry-pick it to develop, without reverting the master, then will be aligned during next release.

**Pull request merged**
