### PR TITLE
Release 2019.07.08

### PR DESCRIPTION
**Pull request by inclement**
I haven't had much time to look at PRs and issues for a few days, but I can't forget the regular scheduled release :p

If anyone is able to check any of the release steps, feel free to mark them off here.

# Release checklist

- [x] Check that the [build is passing](https://travis-ci.org/kivy/python-for-android)
- [x] Run the tests locally via `tox`: this performs some long-running tests that are skipped on Travis.
- [x] Build and run the [on_device_unit_tests](https://github.com/kivy/python-for-android/tree/master/testapps/on_device_unit_tests) app using buildozer. Check that they all pass.
- [x] Build and run the following [testapps](https://github.com/kivy/python-for-android/tree/master/testapps) for arch `armeabi-v7a` and `arm64-v8a`:
  - `python3 setup_testapp_python3_sqlite_openssl.py apk`
    - [x] `armeabi-v7a`
    - [x] `arm64-v8a`
  - `python3 setup_testapp_python2.py apk`
    - [x] `armeabi-v7a`
    - [x] `arm64-v8a`

- [x] Check that the version number is correct

### CODE REVIEW

**Comment by JonasT** [comment]
Is the release / what needs to be tested on the `master` branch right now? Might be useful to add such a note to your "please help test" ticket each time just to make sure everyone is testing the right thing

**Comment by inclement** [comment]
Yep, releasing means merging develop into master, so this pr is what needs testing.

Sorry, you're right that it wasn't clear.

**Comment by inclement** [comment]
Ah, my last reply was by email and I didn't realise I messed up the PR - now changed to merge into master and so showing all the different commits.

**Comment by opacam** [comment]
I checked some of the release steps (and updated the main post):
  - [Travis is happy](https://travis-ci.org/kivy/python-for-android/builds/556014036?utm_source=github_status&utm_medium=notification)
  - Local `tox` tests succeed

Here are the tox results:
```
opacam@DEPOBOX:~/Devel/python-for-android$ tox -- tests/
GLOB sdist-make: /home/opacam/Devel/python-for-android/setup.py
pep8 inst-nodeps: /home/opacam/Devel/python-for-android/.tox/.tmp/package/2/python-for-android-2019.7.8.zip
pep8 installed: appdirs==1.4.3,colorama==0.4.1,entrypoints==0.3,flake8==3.7.7,Jinja2==2.10.1,MarkupSafe==1.1.1,mccabe==0.6.1,pep517==0.5.0,pkg-resources==0.0.0,pycodestyle==2.5.0,pyflakes==2.1.1,python-for-android==2019.7.8,pytoml==0.1.20,sh==1.12.14,six==1.12.0,virtualenv==16.6.1
pep8 run-test-pre: PYTHONHASHSEED='3348511286'
pep8 run-test: commands[0] | flake8 pythonforandroid/ tests/ ci/
py27 inst-nodeps: /home/opacam/Devel/python-for-android/.tox/.tmp/package/2/python-for-android-2019.7.8.zip
py27 installed: appdirs==1.4.3,atomicwrites==1.3.0,attrs==19.1.0,colorama==0.4.1,configparser==3.7.4,contextlib2==0.5.5,enum34==1.1.6,funcsigs==1.0.2,importlib-metadata==0.17,Jinja2==2.10.1,MarkupSafe==1.1.1,mock==3.0.5,more-itertools==5.0.0,pathlib2==2.3.3,pep517==0.5.0,pkg-resources==0.0.0,pluggy==0.12.0,py==1.8.0,pytest==4.5.0,python-for-android==2019.7.8,pytoml==0.1.20,scandir==1.10.0,sh==1.12.14,six==1.12.0,virtualenv==16.6.0,wcwidth==0.1.7,zipp==0.5.1
py27 run-test-pre: PYTHONHASHSEED='3348511286'
py27 run-test: commands[0] | pytest tests
============================================================================================================================= test session starts ==============================================================================================================================
platform linux2 -- Python 2.7.16, pytest-4.5.0, py-1.8.0, pluggy-0.12.0
cachedir: .tox/py27/.pytest_cache
rootdir: /home/opacam/Devel/python-for-android
collected 99 items                                                                                                                                                                                                                                                             

tests/test_androidmodule_ctypes_finder.py ...                                                                                                                                                                                                                            [  3%]
tests/test_archs.py ......                                                                                                                                                                                                                                               [  9%]
tests/test_bootstrap.py .......................                                                                                                                                                                                                                          [ 32%]
tests/test_build.py .                                                                                                                                                                                                                                                    [ 33%]
tests/test_distribution.py ..........                                                                                                                                                                                                                                    [ 43%]
tests/test_graph.py ............................                                                                                                                                                                                                                         [ 71%]
tests/test_logger.py .                                                                                                                                                                                                                                                   [ 72%]
tests/test_pythonpackage.py ....                                                                                                                                                                                                                                         [ 76%]
tests/test_pythonpackage_basic.py .........s                                                                                                                                                                                                                             [ 86%]
tests/test_recipe.py ....                                                                                                                                                                                                                                                [ 90%]
tests/test_util.py .......                                                                                                                                                                                                                                               [ 97%]
tests/recipes/test_gevent.py .                                                                                                                                                                                                                                           [ 98%]
tests/recipes/test_reportlab.py .                                                                                                                                                                                                                                        [100%]

==================================================================================================================== 98 passed, 1 skipped in 455.45 seconds ====================================================================================================================
py3 inst-nodeps: /home/opacam/Devel/python-for-android/.tox/.tmp/package/2/python-for-android-2019.7.8.zip
py3 installed: appdirs==1.4.3,atomicwrites==1.3.0,attrs==19.1.0,certifi==2019.6.16,chardet==3.0.4,colorama==0.4.1,coverage==4.5.3,coveralls==1.8.1,docopt==0.6.2,idna==2.8,importlib-metadata==0.18,Jinja2==2.10.1,MarkupSafe==1.1.1,mock==3.0.5,more-itertools==7.1.0,packaging==19.0,pep517==0.5.0,pkg-resources==0.0.0,pluggy==0.12.0,py==1.8.0,pyparsing==2.4.0,pytest==5.0.0,python-for-android==2019.7.8,pytoml==0.1.20,requests==2.22.0,sh==1.12.14,six==1.12.0,urllib3==1.25.3,virtualenv==16.6.1,wcwidth==0.1.7,zipp==0.5.1
py3 run-test-pre: PYTHONHASHSEED='3348511286'
py3 run-test: commands[0] | coverage run --branch --source=pythonforandroid -m pytest tests
============================================================================================================================= test session starts ==============================================================================================================================
platform linux -- Python 3.7.3, pytest-5.0.0, py-1.8.0, pluggy-0.12.0
cachedir: .tox/py3/.pytest_cache
rootdir: /home/opacam/Devel/python-for-android
collected 99 items                                                                                                                                                                                                                                                             

tests/test_androidmodule_ctypes_finder.py ...                                                                                                                                                                                                                            [  3%]
tests/test_archs.py ......                                                                                                                                                                                                                                               [  9%]
tests/test_bootstrap.py .......................                                                                                                                                                                                                                          [ 32%]
tests/test_build.py .                                                                                                                                                                                                                                                    [ 33%]
tests/test_distribution.py ..........                                                                                                                                                                                                                                    [ 43%]
tests/test_graph.py ............................                                                                                                                                                                                                                         [ 71%]
tests/test_logger.py .                                                                                                                                                                                                                                                   [ 72%]
tests/test_pythonpackage.py ....                                                                                                                                                                                                                                         [ 76%]
tests/test_pythonpackage_basic.py ..........                                                                                                                                                                                                                             [ 86%]
tests/test_recipe.py ....                                                                                                                                                                                                                                                [ 90%]
tests/test_util.py .......                                                                                                                                                                                                                                               [ 97%]
tests/recipes/test_gevent.py .                                                                                                                                                                                                                                           [ 98%]
tests/recipes/test_reportlab.py .                                                                                                                                                                                                                                        [100%]

=============================================================================================================================== warnings summary ===============================================================================================================================
pythonforandroid/util.py:23
  /home/opacam/Devel/python-for-android/pythonforandroid/util.py:23: DeprecationWarning: WgetDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
    urlretrieve = WgetDownloader().retrieve

.tox/py3/lib/python3.7/distutils/__init__.py:4
  /home/opacam/Devel/python-for-android/.tox/py3/lib/python3.7/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

.tox/py3/lib/python3.7/site-packages/jinja2/utils.py:485
  /home/opacam/Devel/python-for-android/.tox/py3/lib/python3.7/site-packages/jinja2/utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping

.tox/py3/lib/python3.7/site-packages/jinja2/runtime.py:318
  /home/opacam/Devel/python-for-android/.tox/py3/lib/python3.7/site-packages/jinja2/runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================================================================================================================== 99 passed, 4 warnings in 386.21 seconds ====================================================================================================================
py3 run-test: commands[1] | coverage report -m
Name                                                                     Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------------------------------------------------
pythonforandroid/__init__.py                                                 1      0      0      0   100%
pythonforandroid/archs.py                                                  140      5     26      5    94%   76-78, 96, 159, 184, 73->76, 95->96, 157->159, 183->184, 254->257
pythonforandroid/bdistapk.py                                                97     97     60      0     0%   1-146
pythonforandroid/bootstrap.py                                              225     16    104      9    92%   34, 112-113, 174-175, 201, 205, 209, 268-269, 283-288, 28->34, 90->88, 200->201, 204->205, 208->209, 267->268, 273->276, 282->283, 297->299
pythonforandroid/bootstraps/__init__.py                                      0      0      0      0   100%
pythonforandroid/bootstraps/empty/__init__.py                                9      0      0      0   100%
pythonforandroid/bootstraps/sdl2/__init__.py                                32      1      4      2    92%   21, 20->21, 46->50
pythonforandroid/bootstraps/service_only/__init__.py                        34      1      4      2    92%   29, 28->29, 44->48
pythonforandroid/bootstraps/webview/__init__.py                             33      1      4      2    92%   26, 25->26, 41->45
pythonforandroid/build.py                                                  573    450    248      6    16%   71, 75, 114, 120-124, 130, 143, 156, 163, 169, 176, 190-410, 450-459, 463-466, 469-470, 476, 484, 488-508, 516, 523-581, 585-592, 596-706, 738-827, 833-868, 878-921, 925-1053, 113->114, 129->130, 142->143, 155->156, 168->169, 729->738
pythonforandroid/distribution.py                                           108      6     48      9    90%   98, 101, 116, 118, 151, 177, 95->98, 100->101, 115->116, 117->118, 119->114, 150->151, 176->177, 181->180, 189->191
pythonforandroid/graph.py                                                  178     18    111      9    91%   34-35, 47, 50, 74, 76, 91, 94-98, 135, 289-292, 300, 321, 335-336, 46->47, 49->50, 73->74, 75->76, 90->91, 134->135, 263->259, 299->300, 319->321
pythonforandroid/logger.py                                                 155     49     60     13    60%   13-15, 18, 40, 73, 83-93, 116, 129-130, 137, 153-154, 158, 171, 180, 183-185, 198, 203-241, 12->13, 17->18, 36->40, 49->56, 115->116, 152->153, 157->158, 167->171, 179->180, 181->198, 182->183, 190->178, 191->178
pythonforandroid/patching.py                                                47     29      4      0    35%   5-7, 11-13, 18, 27-29, 33-35, 39-41, 45-47, 51-53, 57-59, 64, 69-71
pythonforandroid/python.py                                                 170    126     34      0    22%   111-181, 187-214, 217-222, 225-268, 271, 274, 285-290, 299-361, 410, 413-437
pythonforandroid/pythonpackage.py                                          320     93    142     25    68%   52-54, 96, 99, 143-146, 170, 176, 193-194, 201-202, 216, 243-248, 259-261, 279, 311, 324-326, 335-336, 342-343, 376-377, 383, 403-413, 426, 451-532, 608-610, 639, 661-662, 696, 727-732, 785, 95->96, 98->99, 142->143, 166->170, 173->176, 215->216, 235->243, 256->259, 274->279, 276->274, 309->311, 379->383, 391->420, 393->403, 394->396, 420->426, 605->608, 611->650, 634->642, 636->639, 665->669, 695->696, 723->727, 738->740, 783->785
pythonforandroid/recipe.py                                                 673    446    264     10    30%   26-32, 43-44, 116-117, 124-126, 132-185, 202-205, 208-214, 226-230, 245-246, 283-285, 291-297, 300-356, 359-431, 436-438, 446, 459-478, 485, 491-493, 500-502, 510, 526-544, 547-552, 555, 561, 599, 608, 621-625, 644, 647-650, 653, 656-667, 676-682, 685, 688, 691-695, 738-748, 752-760, 764-766, 771-774, 777-820, 823-828, 833-834, 840-857, 860-862, 865-867, 882-884, 887-897, 901-903, 906-910, 919-935, 938-942, 965-967, 970-998, 1001-1007, 1013-1026, 1029-1035, 1038-1080, 1096-1101, 1128-1135, 1141-1144, 25->26, 36->43, 240->238, 244->245, 282->283, 445->446, 560->561, 571->570, 596->599, 607->608
pythonforandroid/recipes/Pillow/__init__.py                                 39     39      2      0     0%   1-59
pythonforandroid/recipes/__init__.py                                         0      0      0      0   100%
pythonforandroid/recipes/android/__init__.py                                46     31     10      0    27%   22-24, 27-83
pythonforandroid/recipes/android/src/android/__init__.py                     1      0      0      0   100%
pythonforandroid/recipes/android/src/android/_ctypes_library_finder.py      35      2     19      5    87%   20, 53, 16->19, 19->20, 49->51, 52->53, 61->56
pythonforandroid/recipes/apsw/__init__.py                                   23     23      0      0     0%   1-34
pythonforandroid/recipes/atom/__init__.py                                    7      7      0      0     0%   1-11
pythonforandroid/recipes/audiostream/__init__.py                            18     18      0      0     0%   2-28
pythonforandroid/recipes/babel/__init__.py                                   9      9      0      0     0%   1-15
pythonforandroid/recipes/boost/__init__.py                                  48     48      6      0     0%   1-104
pythonforandroid/recipes/brokenrecipe/__init__.py                            5      5      0      0     0%   1-9
pythonforandroid/recipes/cdecimal/__init__.py                               16     16      4      0     0%   1-25
pythonforandroid/recipes/cffi/__init__.py                                   34     34      2      0     0%   1-53
pythonforandroid/recipes/cherrypy/__init__.py                                8      8      0      0     0%   1-12
pythonforandroid/recipes/coverage/__init__.py                                9      9      0      0     0%   1-19
pythonforandroid/recipes/cryptography/__init__.py                           15     15      0      0     0%   1-23
pythonforandroid/recipes/cymunk/__init__.py                                  7      7      0      0     0%   1-12
pythonforandroid/recipes/dateutil/__init__.py                                9      9      0      0     0%   1-14
pythonforandroid/recipes/decorator/__init__.py                               9      9      0      0     0%   1-13
pythonforandroid/recipes/enaml/__init__.py                                   8      8      0      0     0%   1-12
pythonforandroid/recipes/enum34/__init__.py                                 12     12      2      0     0%   1-22
pythonforandroid/recipes/ethash/__init__.py                                  5      5      0      0     0%   1-11
pythonforandroid/recipes/evdev/__init__.py                                  13     13      0      0     0%   1-25
pythonforandroid/recipes/feedparser/__init__.py                              8      8      0      0     0%   1-12
pythonforandroid/recipes/ffmpeg/__init__.py                                 53     53      4      0     0%   1-127
pythonforandroid/recipes/ffpyplayer/__init__.py                             19     19      0      0     0%   1-28
pythonforandroid/recipes/ffpyplayer_codecs/__init__.py                       6      6      0      0     0%   1-11
pythonforandroid/recipes/flask/__init__.py                                   9      0      0      0   100%
pythonforandroid/recipes/fontconfig/__init__.py                             13     13      0      0     0%   1-19
pythonforandroid/recipes/freetype/__init__.py                               46     33     10      0    23%   31, 41-60, 63-118
pythonforandroid/recipes/genericndkbuild/__init__.py                        19      7      0      0    63%   14, 17-20, 23-26
pythonforandroid/recipes/gevent-websocket/__init__.py                        8      8      0      0     0%   1-12
pythonforandroid/recipes/gevent/__init__.py                                 20      0      0      0   100%
pythonforandroid/recipes/greenlet/__init__.py                                7      7      0      0     0%   1-11
pythonforandroid/recipes/groestlcoin_hash/__init__.py                        7      7      0      0     0%   1-11
pythonforandroid/recipes/harfbuzz/__init__.py                               31     31      4      0     0%   1-79
pythonforandroid/recipes/hostpython2/__init__.py                             6      0      0      0   100%
pythonforandroid/recipes/hostpython3/__init__.py                             6      0      0      0   100%
pythonforandroid/recipes/hostpython3crystax/__init__.py                     24     13      2      0    42%   13-15, 23, 29-41
pythonforandroid/recipes/icu/__init__.py                                    82     82     10      0     0%   1-152
pythonforandroid/recipes/idna/__init__.py                                    8      8      0      0     0%   1-14
pythonforandroid/recipes/ifaddrs/__init__.py                                37     37      8      0     0%   3-54
pythonforandroid/recipes/ipaddress/__init__.py                               7      7      0      0     0%   1-11
pythonforandroid/recipes/jedi/__init__.py                                    8      8      0      0     0%   1-18
pythonforandroid/recipes/jpeg/__init__.py                                   30     30      2      0     0%   1-78
pythonforandroid/recipes/kivy/__init__.py                                   31     17      8      0    36%   16-28, 34-37, 40-51
pythonforandroid/recipes/kiwisolver/__init__.py                              7      7      0      0     0%   1-11
pythonforandroid/recipes/leveldb/__init__.py                                31     31      4      0     0%   1-47
pythonforandroid/recipes/libcurl/__init__.py                                23     23      0      0     0%   1-40
pythonforandroid/recipes/libexpat/__init__.py                               22     22      0      0     0%   2-38
pythonforandroid/recipes/libffi/__init__.py                                 27     12      2      0    52%   27, 30-45, 50
pythonforandroid/recipes/libgeos/__init__.py                                32     32      0      0     0%   1-44
pythonforandroid/recipes/libglob/__init__.py                                38     38      8      0     0%   5-66
pythonforandroid/recipes/libiconv/__init__.py                               20     20      0      0     0%   1-34
pythonforandroid/recipes/libmysqlclient/__init__.py                         21     21      0      0     0%   1-67
pythonforandroid/recipes/libnacl/__init__.py                                 8      8      0      0     0%   1-12
pythonforandroid/recipes/libogg/__init__.py                                 17     17      0      0     0%   1-26
pythonforandroid/recipes/libpq/__init__.py                                  17     17      0      0     0%   1-26
pythonforandroid/recipes/librt/__init__.py                                  21     21      8      0     0%   1-55
pythonforandroid/recipes/libsecp256k1/__init__.py                           18     18      2      0     0%   1-32
pythonforandroid/recipes/libshine/__init__.py                               18     18      0      0     0%   1-30
pythonforandroid/recipes/libsodium/__init__.py                              24     24      0      0     0%   1-31
pythonforandroid/recipes/libtorrent/__init__.py                             64     64     20      0     0%   1-138
pythonforandroid/recipes/libtribler/__init__.py                              9      9      0      0     0%   1-29
pythonforandroid/recipes/libvorbis/__init__.py                              23     23      0      0     0%   1-37
pythonforandroid/recipes/libx264/__init__.py                                17     17      0      0     0%   1-32
pythonforandroid/recipes/libxml2/__init__.py                                30     30      2      0     0%   1-60
pythonforandroid/recipes/libxslt/__init__.py                                39     39      2      0     0%   1-74
pythonforandroid/recipes/libzbar/__init__.py                                29     29      0      0     0%   1-57
pythonforandroid/recipes/libzmq/__init__.py                                 42     42      0      0     0%   1-80
pythonforandroid/recipes/lxml/__init__.py                                   44     44      4      0     0%   1-66
pythonforandroid/recipes/m2crypto/__init__.py                               26     26      2      0     0%   1-40
pythonforandroid/recipes/matplotlib/__init__.py                             15     15      0      0     0%   2-33
pythonforandroid/recipes/msgpack-python/__init__.py                          7      7      0      0     0%   1-11
pythonforandroid/recipes/mysqldb/__init__.py                                31     31      0      0     0%   1-52
pythonforandroid/recipes/netifaces/__init__.py                               9      9      0      0     0%   1-19
pythonforandroid/recipes/numpy/__init__.py                                  38     38      8      0     0%   1-62
pythonforandroid/recipes/omemo-backend-signal/__init__.py                    9      9      0      0     0%   1-21
pythonforandroid/recipes/omemo/__init__.py                                   9      9      0      0     0%   1-17
pythonforandroid/recipes/openal/__init__.py                                 23     23      2      0     0%   1-39
pythonforandroid/recipes/opencv/__init__.py                                 38     38      2      0     0%   1-133
pythonforandroid/recipes/openssl/__init__.py                                54     36     12      0    27%   60-62, 65, 71-72, 80, 86, 91, 94, 98-102, 105-116, 119-137
pythonforandroid/recipes/pbkdf2/__init__.py                                  5      5      0      0     0%   1-12
pythonforandroid/recipes/pil/__init__.py                                    10     10      0      0     0%   1-23
pythonforandroid/recipes/png/__init__.py                                    30     30      0      0     0%   1-52
pythonforandroid/recipes/preppy/__init__.py                                  8      8      0      0     0%   1-12
pythonforandroid/recipes/protobuf_cpp/__init__.py                           84     84     14      0     0%   1-146
pythonforandroid/recipes/psycopg2/__init__.py                               26     26      2      0     0%   1-50
pythonforandroid/recipes/pyaml/__init__.py                                   8      8      0      0     0%   1-12
pythonforandroid/recipes/pyasn1/__init__.py                                  6      6      0      0     0%   2-11
pythonforandroid/recipes/pycparser/__init__.py                               9      9      0      0     0%   1-16
pythonforandroid/recipes/pycrypto/__init__.py                               29     29      0      0     0%   1-44
pythonforandroid/recipes/pycryptodome/__init__.py                            6      6      0      0     0%   1-10
pythonforandroid/recipes/pyethereum/__init__.py                              7      7      0      0     0%   1-15
pythonforandroid/recipes/pyicu/__init__.py                                  36     36      4      0     0%   1-58
pythonforandroid/recipes/pyjnius/__init__.py                                18      4      0      0    78%   21-24
pythonforandroid/recipes/pyleveldb/__init__.py                               9      9      0      0     0%   1-13
pythonforandroid/recipes/pymunk/__init__.py                                 17     17      0      0     0%   1-22
pythonforandroid/recipes/pynacl/__init__.py                                 16     16      0      0     0%   1-29
pythonforandroid/recipes/pyogg/__init__.py                                   9      9      0      0     0%   1-14
pythonforandroid/recipes/pyopenal/__init__.py                                9      9      0      0     0%   1-14
pythonforandroid/recipes/pyopenssl/__init__.py                               8      8      0      0     0%   2-14
pythonforandroid/recipes/pyproj/__init__.py                                  7      7      0      0     0%   1-11
pythonforandroid/recipes/pyrxp/__init__.py                                   7      7      0      0     0%   1-11
pythonforandroid/recipes/pysdl2/__init__.py                                  6      0      0      0   100%
pythonforandroid/recipes/pysha3/__init__.py                                 21     21      4      0     0%   1-30
pythonforandroid/recipes/python2/__init__.py                                31     14      6      0    46%   54-58, 61-72
pythonforandroid/recipes/python3/__init__.py                                20      6      4      1    62%   28, 46-51, 27->28
pythonforandroid/recipes/python3crystax/__init__.py                         51     31      8      0    34%   25-27, 37-74, 77-91, 94, 98
pythonforandroid/recipes/pytz/__init__.py                                    9      9      0      0     0%   1-15
pythonforandroid/recipes/pyusb/__init__.py                                   9      9      0      0     0%   1-14
pythonforandroid/recipes/pyyaml/__init__.py                                  7      7      0      0     0%   1-11
pythonforandroid/recipes/pyzbar/__init__.py                                 17     17      0      0     0%   1-26
pythonforandroid/recipes/pyzmq/__init__.py                                  28     28      0      0     0%   3-59
pythonforandroid/recipes/regex/__init__.py                                   7      7      0      0     0%   1-12
pythonforandroid/recipes/reportlab/__init__.py                              43      4     12      4    78%   25-27, 46, 15->exit, 24->25, 45->46, 48->exit
pythonforandroid/recipes/requests/__init__.py                                8      8      0      0     0%   1-12
pythonforandroid/recipes/ruamel.yaml/__init__.py                             9      9      0      0     0%   1-13
pythonforandroid/recipes/scrypt/__init__.py                                 17     17      0      0     0%   1-26
pythonforandroid/recipes/sdl2/__init__.py                                   18      6      0      0    67%   16-19, 22-25
pythonforandroid/recipes/sdl2_image/__init__.py                              7      0      0      0   100%
pythonforandroid/recipes/sdl2_mixer/__init__.py                              7      0      0      0   100%
pythonforandroid/recipes/sdl2_ttf/__init__.py                                6      0      0      0   100%
pythonforandroid/recipes/secp256k1/__init__.py                              16     16      0      0     0%   1-30
pythonforandroid/recipes/setuptools/__init__.py                              8      0      0      0   100%
pythonforandroid/recipes/shapely/__init__.py                                13     13      0      0     0%   1-22
pythonforandroid/recipes/simple-crypt/__init__.py                            7      7      0      0     0%   1-11
pythonforandroid/recipes/six/__init__.py                                     6      0      0      0   100%
pythonforandroid/recipes/snappy/__init__.py                                  7      7      0      0     0%   1-13
pythonforandroid/recipes/spine/__init__.py                                   9      9      0      0     0%   1-14
pythonforandroid/recipes/sqlalchemy/__init__.py                              9      9      0      0     0%   1-15
pythonforandroid/recipes/sqlite3/__init__.py                                22      9      0      0    59%   14, 17-20, 24-26, 30-32
pythonforandroid/recipes/storm/__init__.py                                  12     12      0      0     0%   1-22
pythonforandroid/recipes/sympy/__init__.py                                   8      8      0      0     0%   2-16
pythonforandroid/recipes/twisted/__init__.py                                16     16      0      0     0%   1-29
pythonforandroid/recipes/ujson/__init__.py                                   6      6      0      0     0%   1-10
pythonforandroid/recipes/vispy/__init__.py                                   7      7      0      0     0%   1-14
pythonforandroid/recipes/vlc/__init__.py                                    49     49     12      0     0%   1-75
pythonforandroid/recipes/websocket-client/__init__.py                        6      6      0      0     0%   1-27
pythonforandroid/recipes/wsaccel/__init__.py                                 7      7      0      0     0%   1-11
pythonforandroid/recipes/x3dh/__init__.py                                   10     10      0      0     0%   1-18
pythonforandroid/recipes/xeddsa/__init__.py                                 19     19      0      0     0%   1-33
pythonforandroid/recipes/zbar/__init__.py                                   18     18      0      0     0%   1-33
pythonforandroid/recipes/zbarlight/__init__.py                              17     17      0      0     0%   1-26
pythonforandroid/recipes/zeroconf/__init__.py                                8      8      0      0     0%   1-12
pythonforandroid/recipes/zope/__init__.py                                   14     14      0      0     0%   2-27
pythonforandroid/recipes/zope_interface/__init__.py                         21     21      0      0     0%   1-31
pythonforandroid/recommendations.py                                         53     33     18      0    28%   19-35, 40-59, 80-89, 99-107
pythonforandroid/toolchain.py                                              552    462    208      2    13%   42-51, 57-58, 60-62, 65-66, 106-128, 140-153, 161, 174-212, 217-219, 231, 238-666, 670-673, 682-704, 708-718, 722-725, 730-739, 742-769, 775-779, 783-798, 803-805, 810-812, 816-817, 832-839, 850-854, 864-879, 889-899, 903-905, 911-1061, 1068, 1072-1075, 1079, 1084-1092, 1096-1101, 1110-1120, 1127, 1132, 1137-1150, 1154-1178, 1182-1185, 59->60, 64->65
pythonforandroid/util.py                                                    65      2     22      4    93%   11-12, 65->67, 67->69, 69->71, 117->119
--------------------------------------------------------------------------------------------------------------------
TOTAL                                                                     6226   4254   1598    108    31%
___________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________
  pep8: commands succeeded
  py27: commands succeeded
  py3: commands succeeded
  congratulations :)
```

**Comment by AndreMiras** [comment]
Awesome!
I'm not super available lately unfortunately, but I'm just about to give the release a try. I'll edit this comment later to say if things went OK

**Comment by inclement** [comment]
@AndreMiras Great, I've just finished the tests and am looking to merge as soon as travis is happy.

**Comment by inclement** [comment]
arm64-v8a build failed for some reason, I've restarted it.

**Comment by AndreMiras** [comment]
> arm64-v8a build failed for some reason, I've restarted it.

Too bad, what was the error? Anything known and already listed here https://github.com/kivy/python-for-android/issues/1306 ?

**Comment by inclement** [comment]
It was a failure patching pyjnius I think, I didn't look that closely.

**Comment by AndreMiras** [comment]
Rings the bell, as if it was downloading/cloning the wrong version of pyjnius and then fails at patching it :thinking: 
Anyway we should probably bump a pyjnius 1.2.1 and link to that, with eventually checksum. Let's keep that for later

**Comment by inclement** [comment]
Passed this time, release merged :)

**Pull request merged**
