### PR TITLE
reciepes for freetype and harfbuzz

### PR DESCRIPTION
**Pull request by olymk2**
reciepe for freetype and harfbuzz libraries allows freetype python file to be imported.

### CODE REVIEW

**Comment by tito** [comment]
Freetype is one of the already checkout in src/jni. Why do you need to have it again?

**Comment by olymk2** [comment]
not sure what you mean from what i could figure out i could not import freetype into my python program i tried different required libraries etc and asked around but got the impression it was not available so ported this.
I am using it specifically for creating font outlines if there is something i can add to buildozer.spec and import into python then great :)

**Comment by olymk2** [comment]
on second thought are you saying i can just change the reciepe to look for freetype in another location ?

**Comment by olymk2** [comment]
@tito okay i tried this looks like the freetype code in src/jni is different some how.

they will not build outside of py4a 

copying the files to python-for-android/build/freetype and then entering that folder before running

autogen.sh gives me 

You must be in the same directory as `autogen.sh'.
Bootstrapping doesn't work if srcdir != builddir.

running configure gives me 

Makefile:32: builds/toplevel.mk: No such file or directory
make: *** No rule to make target 'builds/toplevel.mk'. Stop.

so using the existing code may not be an option unless you might know why ?

**Comment by tito** [comment]
Thanks!

**Pull request merged**
