### PR TITLE
Crystax support for Feedparser

### PR DESCRIPTION
**Pull request by kuzeyron**
In this PR I've added support for Feedparser to work with python3crystax.

### CODE REVIEW

**Comment by AndreMiras** [comment]
Hi @kuzeyron thanks for the pull request. Could you please fix a couple of issues:

- tox is failing, simply run `tox` from the root path and it will point you to the errors
- if this pull request is just about changing this line: `depends = [('hostpython2', 'python3crystax'), 'setuptools']` please keep it noise-free by not moving line around and avoiding changing space by tabs. It might just be an editor issue.
- last, I think this could easily be just one single commit rather than two. Basically you need to squash them. If you don't know how to do it all, give us write access to your pull request and we can do it for you.

**Comment by kuzeyron** [comment]
@AndreMiras I edited that line in the webbrowser. Then I made a pull request through git. But I can't see it anywhere. I don't think I changed the whitespace on the file. Only directly added the crystax part.

**Comment by AndreMiras** [comment]
OK I see, it's a good opportunity for you to learn a bit more about git/GitHub and the shell.
Basically if you used the online editor, what it does is it creates a fork. So you can simply clone it:
```sh
git clone git@github.com:kuzeyron/python-for-android.git
```
And then work on it, the workflow should be something like:
```sh
cd python-for-android/
git reset --soft HEAD~1
vim pythonforandroid/recipes/feedparser/__init__.py
tox
git add pythonforandroid/recipes/feedparser/__init__.py
git commit --amend
```
Basically the `git reset --soft HEAD~1` will squash your two commits and create only one. Then you edit with your favorite editor (vim obviously). Then you run the `tox` test to make sure you didn't introduce any regression. Then you cheat the commit log with `git add && git commit --amend`.
Feel free to Google the commands you didn't understand to find out more.

**Comment by KeyWeeUsr** [comment]
@kuzeryon @AndreMiras https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing let git do the work :) also, git's documentation is quite nice nowadays.

**Comment by AndreMiras** [comment]
@kuzeyron ping :smile: 
Do you still have interest with this PR? I think it's a useful one, but we jus want to keep the source control clean. If you struggle with rebasing and squashing feel free to create just a new PR with just that simple change.

**Comment by kuzeyron** [comment]
Hey André! I haven't had any interests in trying to re-PR the Feedparser.
I'm doing other projects so my time is being spent on them instead.
Feel free to fix that part!

**Comment by AndreMiras** [comment]
Thanks @kuzeyron for the feedback.
I've created the follow up pull request here https://github.com/kivy/python-for-android/pull/1376

**Pull request closed without merging**
