### PR TITLE
Extend numpy recipe to support python3

### LINKED ISSUE #882: Numpy support w/ python3crystax
I'm trying to get my app to compile with Python 3 using the Crystax NDK.  Everything is set up, and if I try to push my app to my device without specifying that numpy is needed, everything works fine.  However, numpy raises a few issues:
1. (easily fixed) The recipe needs to be modified such that python3crystax is supported.  Currently, it only claims python2 support, but that's overridden easily enough (`depends = ['python2']` -> `depends = [('python3crystax', 'python2)]` in the `__init__.py`).
2. The compiler claims it can't find -lcrystax:

``` sh
...
don't know how to compile Fortran code on platform 'posix'
C compiler: /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/wwoods/walt/dev/kivy/crystax-ndk-10.3.2/platforms/android-19/arch-arm -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/wwoods/walt/dev/kivy/crystax-ndk-10.3.2/platforms/android-19/arch-arm -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/wwoods/miniconda3/envs/kivy/include/python3.5m -c'
ccache: _configtest.c
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/wwoods/walt/dev/kivy/crystax-ndk-10.3.2/platforms/android-19/arch-arm _configtest.o -o _configtest
/home/wwoods/walt/dev/kivy/crystax-ndk-10.3.2/toolchains/arm-linux-androideabi-5/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/5.3/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lcrystax
collect2: error: ld returned 1 exit status
/home/wwoods/walt/dev/kivy/crystax-ndk-10.3.2/toolchains/arm-linux-androideabi-5/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/5.3/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lcrystax
collect2: error: ld returned 1 exit status
failure.
removing: _configtest.c _configtest.o
```

Everything except numpy works fine, so I think that it's just Numpy's recipe that needs a minor alteration.  Oddly though, specifying a LIBRARY_PATH or LDFLAGS does not have any effect.  In fact, if I add a `get_recipe_env` to the `NumpyRecipe` that prints out what `super().get_recipe_env(arch)` contains, it has LDFLAGS with the appropriate path on there.  Running the linker by hand with the given flags find the library fine (`ld $(LDFLAGS) -lcrystax --verbose`).  In the context of python-for-android though, the linker always fails to find libcrystax.a.

Any help appreciated, thanks.

### PR DESCRIPTION
**Pull request by krinnewitz**
This PR extends the existing numpy recipe to also support
python3crystax. Additionally, the existing recipe code is cleaned up a
bit and numpy is upgraded to version 1.15.1.

The existing patches were ported to the new numpy version.
To get numpy 1.15.1 working with python 2.7, an additional patch
was necessary.

This PR should resolve #882.

### CODE REVIEW

**Comment by krinnewitz** [comment]
Thanks so far @AndreMiras. Since no one has picked up on this, yet - here is a very simple program that can be used as a quick starting point:

```
import sys
print ('sys.version is', sys.version)

import numpy as np
a = np.arange(15).reshape(3, 5)
print('numpy seems to work:\n', a)
```

**Comment by AndreMiras** [comment]
Thanks for the reminder, merged!

**Comment by AntoniRomera** [comment]
Hi, when i use this code, i got the next error:

```
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mfloat-abi=softfp'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mfpu=vfp'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mthumb'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mfloat-abi=softfp'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mfpu=vfp'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mthumb'
```

**Comment by johnbolia** [comment]
First of all thank you very much to krinnewitz for getting the Python 3 build going. It has been an open ticket for so long.

As it seems python3crystax is being dropped in favor of python3 (Google NDK). The numpy recipe only has python2 and python3crystax. Does the recipe use any functions that are specific to crystax?

**Comment by krinnewitz** [comment]
I think porting/extending the recipe for google NDK's python3 shouldn't be a problem.

**Comment by johnbolia** [comment]
If somebody could take this on it would be super helpful, I have had a look
and it is out of my depth.

I am caught in that I need both SSL and Numpy. Crystax doesn't support SSL
easily. So I have been using python2, but my AWS module boto is getting old
and buggy. So a non-crystax python 3 would get me out of this squeeze.

**Comment by AndreMiras** [comment]
@johnbolia start a "WIP" pull request that try the fix and share your problem in that dedicated PR, we can also give support on Discord to help you building it

**Pull request merged**
