### PR TITLE
Release 2020.03.30

### PR DESCRIPTION
**Pull request by inclement**
Let's have a last release branch before the upcoming set of breaking PRs.

-   [ ] Check that the [build is passing](https://travis-ci.org/kivy/python-for-android)
-   [x] Run the tests locally via tox: this performs some long-running tests that are skipped on Travis.
-   [x] Build and run the [on_device_unit_tests](https://github.com/kivy/python-for-android/tree/master/testapps/on_device_unit_tests) app using buildozer. Check that they all pass.
-    [x] Check that the version number is correct

### CODE REVIEW

**Comment by inclement** [comment]
Still not sure why there are conflicts here...

**Comment by rnixx** [comment]
> Still not sure why there are conflicts here...

master is 3 commits ahead of develop, develop probably needs to be rebased against b1f6064d9644a532f52728218e42da37d54f502c

**Comment by AndreMiras** [comment]
Thanks @rnixx I gave a try to what you said https://github.com/kivy/python-for-android/pull/2120
No sure what happened in master indeed

**Comment by inclement** [comment]
Merge conflicts resolved by merging from master.

**Comment by inclement** [comment]
I intend to finish testing and release at the weekend.

**Comment by AndreMiras** [comment]
Awesome! Yes I'll also test some apps there

**Comment by AndreMiras** [comment]
I've just tested with an app that has ~50 requirements and things are working OK

**Comment by inclement** [comment]
@AndreMiras If you think we're good to merge, please go ahead, I haven't checked the details but your test sounds good. I'll try to update with instructions about the new on_device_unit_tests app method before the next release.

**Comment by AndreMiras** [comment]
Ran `on_device_unit_tests` OK :heavy_check_mark: using buildozer and `p4a.branch = release-2020.03.30`
```
04-04 20:26:40.415 18674 18731 I python  : Android kivy bootstrap done. __name__ is __main__
04-04 20:26:40.415 18674 18731 I python  : AND: Ran string
04-04 20:26:40.415 18674 18731 I python  : Run user program, change dir and execute entrypoint
04-04 20:26:40.934 18674 18731 I python  : Imported unittest
04-04 20:26:40.934 18674 18731 I python  : Defined test case
04-04 20:26:40.937 18674 18731 I python  : Imported unittest
04-04 20:26:40.937 18674 18731 I python  : Defined test case
04-04 20:26:40.937 18674 18731 I python  : 
04-04 20:26:40.937 18674 18731 I python  : ----------------------------------------------------------------------
04-04 20:26:40.938 18674 18731 I python  : Ran 0 tests in 0.000s
04-04 20:26:40.938 18674 18731 I python  : 
04-04 20:26:40.938 18674 18731 I python  : OK
04-04 20:26:40.938 18674 18731 I python  : Ran tests
04-04 20:26:41.021 18674 18731 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.kivy.p4aunittests/files/app/.kivy/logs/kivy_20-04-04_1.txt
04-04 20:26:41.022 18674 18731 I python  : [INFO   ] [Kivy        ] v1.11.1
04-04 20:26:41.022 18674 18731 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.kivy.p4aunittests/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
04-04 20:26:41.023 18674 18731 I python  : [INFO   ] [Python      ] v3.8.1 (default, Apr  4 2020, 20:13:10) 
04-04 20:26:41.023 18674 18731 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
04-04 20:26:41.023 18674 18731 I python  : [INFO   ] [Python      ] Interpreter at ""
04-04 20:26:41.985 18674 18731 I python  : .[INFO   ] [Factory     ] 184 symbols loaded
04-04 20:26:42.581 18674 18731 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
04-04 20:26:42.663 18674 18731 I python  : [INFO   ] [Window      ] Provider: sdl2
04-04 20:26:42.700 18674 18731 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
04-04 20:26:42.702 18674 18731 I python  : [INFO   ] [GL          ] Backend used <sdl2>
04-04 20:26:42.702 18674 18731 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 v1.r12p1-04bet0.1bb9662be2ebee934dcbd7265c794a91'>
04-04 20:26:42.704 18674 18731 I python  : [INFO   ] [GL          ] OpenGL vendor <b'ARM'>
04-04 20:26:42.704 18674 18731 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Mali-T830'>
04-04 20:26:42.705 18674 18731 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
04-04 20:26:42.706 18674 18731 I python  : [INFO   ] [GL          ] Texture max size <8192>
04-04 20:26:42.706 18674 18731 I python  : [INFO   ] [GL          ] Texture max units <16>
04-04 20:26:42.759 18674 18731 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
04-04 20:26:42.760 18674 18731 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
04-04 20:26:43.169 18674 18731 I python  : .........
04-04 20:26:43.169 18674 18731 I python  : ----------------------------------------------------------------------
04-04 20:26:43.169 18674 18731 I python  : Ran 10 tests in 2.228s
04-04 20:26:43.169 18674 18731 I python  : 
04-04 20:26:43.169 18674 18731 I python  : OK
04-04 20:26:43.169 18674 18731 I python  : Ran tests
04-04 20:26:43.170 18674 18731 I python  : Python for android ended.
```

**Comment by AndreMiras** [comment]
`tox` is also green, see [tox.log](https://github.com/kivy/python-for-android/files/4432254/tox.log) attached

**Comment by inclement** [comment]
Yay, thanks @AndreMiras. Do you want to try to push it to pypi or shall I do that?

**Comment by AndreMiras** [comment]
I'll try to thanks, I also need to merge back to develop, tag and probably bump and make the `post0` change, but got sidetracked

**Comment by AndreMiras** [comment]
Published `v2020.03.30` tag and uploaded release to PyPI https://pypi.org/project/python-for-android/2020.3.30/
```
git fetch --all --prune
git checkout master
git reset --hard upstream/master
rm -rf dist/ build/
python setup.py sdist bdist_wheel
twine upload dist/python* --verbose
```

**Pull request merged**
