### PR TITLE
Add hardware acceleration codecs to ffmpeg recipe

### PR DESCRIPTION
**Pull request by brentpicasso**

### CODE REVIEW

**Review by AndreMiras — COMMENTED** [review]
LGTM, just the title is misleading, it says bump recipes version, but all I see are the hardware acceleration codecs enabled right? I imagine the bump was reverted in subsequent commits.
Having the PR rebased & squashed would be a real plus, otherwise no worry I can try to think about it at merge time.
image

**Comment by brentpicasso** [comment]
@AndreMiras I think the original work was to bump the recipe versions, and also to add these codecs. 

It seems that develop received these updated versions, and this PR left behind only the hardware codecs.   @DexerBR do you agree with this assessment?

I updated the title to match the new reality.

**Comment by DexerBR** [comment]
> @AndreMiras I think the original work was to bump the recipe versions, and also to add these codecs.
> 
> It seems that develop received these updated versions, and this PR left behind only the hardware codecs. @DexerBR do you agree with this assessment?
> 
> I updated the title to match the new reality.

I agree, the versions have been updated in this PR: https://github.com/kivy/python-for-android/pull/3065

@brentpicasso How about updating the title to "Add hardware acceleration codecs to `ffmpeg` recipe"?

**Comment by brentpicasso** [comment]
> @brentpicasso How about updating the title to "Add hardware acceleration codecs to `ffmpeg` recipe"?

@DexerBR  done!

**Review by AndreMiras — APPROVED** [review]

**Pull request merged**
