### PR TITLE
Adds zbar (and dependencies) support, refs #854

### PR DESCRIPTION
**Pull request by AndreMiras**
- zbar Python extension
  - zbar library
  - iconv library

### CODE REVIEW

**Comment by AndreMiras** [comment]
This is a first working draft, however it doesn't currently have the ImageMagick support.

**Comment by AndreMiras** [comment]
Here's a demo application using it:
https://github.com/AndreMiras/garden.zbarcam

**Comment by inclement** [comment]
Sorry for the delay getting to this, it looks great, I should be able to test and merge at the weekend.

**Comment by inclement** [comment]
Not quite the weekend I intended, but all checked now and it worked great. Thanks!

I did have to add `import PIL.Image` to the zbar example app for it to run.

**Comment by AndreMiras** [comment]
Great thanks and good to know for the import.

**Comment by EderSant** [comment]
AndreMiras I know this topic has nothing to do with the library I'm needing, but I'm having trouble creating a dlib library recipe. Would you help me?

**Comment by EderSant** [comment]
@AndreMiras I know this topic has nothing to do with the library I'm needing, but I'm having trouble creating a dlib library recipe. Would you help me?

**Comment by AndreMiras** [comment]
Hi @EderSant `dlib` looks like an exciting library. Try on Discord support or dev channel.
What I recommend you is giving a try creating it yourself, following https://python-for-android.readthedocs.io/en/latest/recipes/ and also seeing what's being done on recent C/C++ recipes.
You may obviously get some compilation or other type of errors, but most of the time nothing so special or uncovered, but if you're stuck you can share your draft recipe code and share the full error log on Discord. If one dev/contributor is available he would probably be glad to help.
Best luck!

**Pull request merged**
