### PR TITLE
Fix issue #2630

### PR DESCRIPTION
**Pull request by Neizvestnyj**
Now, if the **requirements** has not been changed, the reassembly will not occur

### CODE REVIEW

**Comment by mzakharo** [comment]
the fix does not make sense to me. ` install_in_hostpython = True` is a directive to build the recipe twice, once for target arch, and once for host arch. You would only need to build for hostpython if some other recipe  has a build dependency on tflite-runtime, which to my knowledge, is not the cause of issue #2630.

  Many recipes dont have this 'install_in_hostpython' directive, and do not exhibit issue #2630  .

Am I missing something?

**Comment by Neizvestnyj** [comment]
> the fix does not make sense to me. ` install_in_hostpython = True` is a directive to build the recipe twice, once for target arch, and once for host arch. You would only need to build for hostpython if some other recipe has a build dependency on tflite-runtime, which to my knowledge, is not the cause of issue #2630.
> 
> Many recipes dont have this 'install_in_hostpython' directive, and do not exhibit issue #2630 .
> 
> Am I missing something?

It's really strange, but you can check if for some reason the package stops being reassembled

**Comment by AndreMiras** [comment]
Agree, what should be looked into instead is probably the [`PythonRecipe.should_build()`](https://github.com/kivy/python-for-android/blob/v2022.03.13/pythonforandroid/recipe.py#L950-L956).
You can override this function in your recipe, put a breakpoint and step into `super().should_build(arch)`.
My guess would be there's some kind of mismatch between the recipe name and what's to be expected in that folder, well something like that.
But that requires a bit of digging

**Comment by Neizvestnyj** [comment]
> Agree, what should be looked into instead is probably the [`PythonRecipe.should_build()`](https://github.com/kivy/python-for-android/blob/v2022.03.13/pythonforandroid/recipe.py#L950-L956). You can override this function in your recipe, put a breakpoint and step into `super().should_build(arch)`. My guess would be there's some kind of mismatch between the recipe name and what's to be expected in that folder, well something like that. But that requires a bit of digging

Done

**Review by misl6 — CHANGES_REQUESTED** [review]
Hi @Neizvestnyj 

Seems that the PEP8 tests are failing (and so also the other tests), can you take care of it?

**Review by tshirtman — APPROVED** [review]

**Pull request merged**
