### PR TITLE
Recipe for OpenCV

### LINKED ISSUE #75: Camera on android
Log error: http://pastebin.com/LwgjpMqQ

. / distribute.sh-m "pil Kivy pygame opencv"

error: Recipe opencv does not exit

opencv is not included in the "recipes dir".

How to fix it?
Thank you.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/115409-camera-on-android?utm_campaign=plugin&utm_content=tracker%2F11371&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F11371&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jasonxunxu**
This is a fully working recipe for OpenCV (v2.4.10.1). The recipe automatically builds OpenCV Python module (cv2.so) and installs native camera libraries. This recipe attempts to fix #75.

### CODE REVIEW

**Comment by gorgonaut04** [comment]
Well this is exciting, looking forward to trying it!

**Comment by gorgonaut04** [comment]
Hi Jason, I tried adding the new opencv recipe folder to my kivy linux virtual machine. When building my app with the "buildozer android debug" command, using the packages "numpy,opencv,kivy" in buildozer.spec, I get the error (paraphrasing because I don't have it in front of me): 
"command failed: pip install [some_path] [another_path] opencv"

Obviously, pip shouldn't be used in order to generate the opencv lib, since it's not a listed package. Any suggestions/tips on how I can include this recipe before your pull request is accepted?

**Comment by jasonxunxu** [comment]
That's strange, when a recipe exists pip should not be activated to install that package, can you run:
``buildozer -v android debug``
and paste the log somewhere?

**Comment by gorgonaut04** [comment]
I was suspicious of what directory is being used. I will investigate this, but it might be a couple days. This would certainly seem to explain the issue. Thanks for the response!

**Comment by gorgonaut04** [comment]
The directory was indeed incorrect (pointing to default) I added the new OpenCV recipe folder to the /home/kivy/buildozer/.buildozer/android/platform/python-for-android/recipes/ path, ran it again, and got: 
Read plyer recipe
Module plyer depend on pyjnius android
Read numpy recipe
Module numpy depend on python
Read opencv recipe
/home/kivy/buildozer/.buildozer/android/platform/python-for-android/recipes/opencv/recipe.sh: line 2: $'\r': command not found
/home/kivy/buildozer/.buildozer/android/platform/python-for-android/recipes/opencv/recipe.sh: line 5: $'\r': command not found
/home/kivy/buildozer/.buildozer/android/platform/python-for-android/recipes/opencv/recipe.sh: line 10: $'\r': command not found
/home/kivy/buildozer/.buildozer/android/platform/python-for-android/recipes/opencv/recipe.sh: line 14: $'\r': command not found
/home/kivy/buildozer/.buildozer/android/platform/python-for-android/recipes/opencv/recipe.sh: line 15: syntax error near unexpected token `$'{\r''
/home/kivy/buildozer/.buildozer/android/platform/python-for-android/recipes/open'v/recipe.sh: line 15: `function prebuild_opencv() {
Module opencv depend on (numpy python)
Read kivy recipe
Module kivy depend on pygame pyjnius android
Read pyjnius recipe
Module pyjnius depend on python sdl
Read android recipe
Module android depend on pygame
Read python recipe
Module python depend on hostpython
Read (numpy recipe
Recipe (numpy does not exist, adding the module as pure-python package
 recipethon)
 does not exist, adding the module as pure-python package
Read pygame recipe
Module pygame depend on python sdl
Ignored pyjnius, already processed
Ignored android, already processed
Ignored python, already processed
Read sdl recipe
Module sdl depend on python
Ignored pygame, already processed
Read hostpython recipe
Ignored python, already processed
Ignored sdl, already processed
Ignored python, already processed
Modules changed to (numpy hostpython python) opencv python numpy sdl pygame pyjnius android kivy plyer
Pure-Python modules changed to (numpy python)
Run get packages
./distribute.sh: eval: line 534: syntax error near unexpected token `('
./distribute.sh: eval: line 534: `echo $P4A_(numpy_DIR'
Download package for (numpy
No package for (numpy
Download package for hostpython
Module hostpython already downloaded
./distribute.sh: eval: line 534: syntax error near unexpected token `)'
./distribute.sh: eval: line 534: `echo $P4A_python)_DIR'
Download package for python)
No package for python)
Download package for opencv
.ziploading https://github.com/Itseez/opencv/archive/2.4.10.1
--2015-02-21 02:08:27--  https://github.com/Itseez/opencv/archive/2.4.10.1%0D.zip%0D
Resolving github.com (github.com)... 192.30.252.128
Connecting to github.com (github.com)|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-02-21 02:08:28 ERROR 404: Not Found.

**Comment by jasonxunxu** [comment]
I suggest to do the following:
1. Check out [my p4a fork](https://github.com/jasonxunxu/python-for-android) directly instead of copying the opencv recipe out of it to avoid encoding problems.
2. Use p4a directly without buildozer, it will simply things and let you know whether p4a works fine itself.

**Comment by gorgonaut04** [comment]
using your p4a fork worked! It has built, now to see how it works compared to my PC kivy app! PIL had some problematic filter differences, so we'll see!

**Comment by gorgonaut04** [comment]
Okay, it's working great! I have questions if you're willing to share how you used the android camera feature, but I'll save those for the the other thread about OpenCV support

**Comment by tito** [comment]
That's neat!!!

**Pull request merged**
