### PR TITLE
Add 'enable-ssl.patch' to Python2Recipe.patches

### PR DESCRIPTION
**Pull request by Polynomdivision**
This PR is supposed to fix the issue that ssl cannot be imported in python2 
See issue #934

### CODE REVIEW

**Comment by inclement** [comment]
I was looking into this to understand it better, and I think this patch is supposed to be unnecessary following https://github.com/kivy/python-for-android/pull/838/files , but I'm not really sure. I've never used openssl directly myself, so I'll try to test it just to be sure.

**Comment by Polynomdivision** [comment]
Maybe this helps to reproduce it: If I try to import (python2) ssl or use a package that imports ssl, I always got the error that `_ssl` cannot be found (See #934, like in the original PR description).
But I'm not sure it it's a bug/erorr in p4a or just my incredible ability to break every piece of software I touch.

**Comment by brussee** [comment]
Wether you can use openssl directly is not changed by #838. Packages that link to openssl, as you can see in #838, do so dynamically. If you find a package that fails to import ssl you need to link it at compile time or use the 'enable-ssl.patch', I think.

**Comment by Fak3** [comment]
This maybe a fix for https://github.com/kivy/python-for-android/issues/850 I will try to check when i have time

**Comment by frankgould** [comment]
I tried this patch and got the same error (below) after the patch.

E/dalvikvm( 3869): dlopen("/data/app-lib/com.masterpics.slideshow-1/libpython2.7.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libssl1.0.2h.so" needed by "libpython2.7.so"; caused by load_library(linker.cpp:745): library "libssl1.0.2h.so" not found

**Comment by frankgould** [comment]
Are there any suggestions to fix this problem? I'm still getting the same error and can't find a solution online.

**Comment by KeyWeeUsr** [comment]
@frankgould see [this answer](http://stackoverflow.com/a/28817942/5994041). Basically it means that 4.2 isn't able to load libs automatically, so we do it [here](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonUtil.java#L31) instead.

**Comment by frankgould** [comment]
Hi KeyWeeUsr, thanks for your quick response. I tried several different compiles with PythonUtil.java edited with the additional "load" code but these all errored out by not finding the names.
                System.loadLibrary(openssl);
                System.loadLibrary(pyopenssl);
                System.loadLibrary(libssl);

So, I grep searched for libpythonXXX.so and found 5 copies of PythonUtil.java, some did not have the System.loadLibrary(lib), which I added and rebuilt. Now the error is "Cannot load library: find_library(linker.cpp:889): "/data/app-lib/com.masterpics.slideshow-1/libpython2.7.so" failed to load previously."

I wasn't sure if it is helpful but below are recipes I am using.
includes recipes (hostpython2, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, python2, numpy, sdl2, setuptools, six, android, opencv, pyjnius, pyopenssl, kivy), built for archs (armeabi-v7a)

My buildozer.spec requirements are:
requirements = kivy,openssl,pyopenssl,hostpython2,opencv,android

Thanks again for your help.

**Comment by frankgould** [comment]
Please let me know if there is anything else I can provide to help with this.  Thanks.

**Comment by frankgould** [comment]
Is there somewhere I can find more information to solve this problem? I am waiting patiently for some guidance.

**Comment by frankgould** [comment]
I was able to solve this using the information from the following link:
https://github.com/kivy/python-for-android/pull/903

**Comment by Bakterija** [comment]
I just used this to enable ssl in gevent . Otherwise it complains about missing _ssl

**Comment by Zen-CODE** [comment]
This change did not fix the issue 850 for me.

https://github.com/kivy/python-for-android/issues/850

**Comment by AndreMiras** [comment]
This is rather old and conflicting with recent p4a refactoring, e.g. https://github.com/kivy/python-for-android/pull/1537
Feel free to open a new one if needed

**Pull request closed without merging**
