### PR TITLE
Python 2.7.2 doesn't build cleanly with GCC ≥ 4.8

### PR DESCRIPTION
**Pull request by kronenpj**
I propose this patch as a solution.to issue #321.

### CODE REVIEW

**Comment by inclement** [comment]
Looks like I'm using gcc 5.1, and I haven't had a problem - how do you find it doesn't build cleanly?

The patch seems fairly innocuous, but I'm not sure if I can test it.

**Comment by kronenpj** [comment]
I too am using GCC 5.1 (5.1.1 actually).  It's related to a python issue that's been fixed in more recent versions, but not in Python 2.7.2: http://bugs.python.org/issue17547.

Can you try on a different machine / VM or in some other way make sure that you're not re-using a working build or environment? 

I'd started to update to Python 2.7.4 or later but the codebase was too different for the time I had available.

**Comment by inclement** [comment]
I'm fairly sure I'm not using an old working build as I've rebuilt
python many times recently. I'll check out the issue though, and may
come across it anyway since I was going to test some builds in a VM.

**Comment by kronenpj** [comment]
Fair enough.  I had another thought, it may be that Fedora (my distro) and others mentioned in the Python issue adopted removal of -Wformat but your distribution re-added it to avoid such breakage.

**Comment by inclement** [comment]
For what it's worth, I use Arch Linux - I wouldn't usually expect such a patch but it's not impossible.

I read the python bug and it does seem like I should see it, and probably so should other people, but I haven't seen anyone report the problem. Weird.

**Comment by kronenpj** [comment]
Agreed, I'm usually not the one to find these things the first time :smile:

**Comment by AndreMiras** [comment]
Hello @kronenpj thanks for the patch and sorry we couldn't make it to the tree.
This is rather old and built on the old toolchain.
Also that patch was integrated in 34e269e52 since then.

**Pull request closed without merging**
