### PR TITLE
Python 391 support

### PR DESCRIPTION
**Pull request by kuzeyron**
With these changes Python 3.9.1 should be able to run on your devices.

In order to run 3.9.1 on your device:
`requirements = python3==3.9.1,hostpython3==3.9.1,kivy==master,setuptools==51.1.1,cython==0.29.21`

My example code to run:
```
import platform
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):

    def build(self):
        return Button(
            text=f'hello world - {platform.python_version()}')

if __name__ == '__main__':
    TestApp().run()
```

### CODE REVIEW

**Comment by obfusk** [comment]
There was already a PR for that: #2337 :)

**Comment by kuzeyron** [comment]
> There was already a PR for that: #2337 :)

Obviously your PR is going to step on a few land mines. At least for those who is running 3.9.1 on their systems.

**Comment by obfusk** [comment]
#2394 has been merged :)

**Comment by misl6** [comment]
Superseded by #2394.

**Pull request closed without merging**
