### PR TITLE
Added ability to set input type on android

### PR DESCRIPTION
**Pull request by dwmoffatt**
This adds the ability to set input type of keyboard on android.

### CODE REVIEW

**Comment by AndreMiras** [comment]
Very cool thanks! I don't have time to test it lately, but would you mind rebasing on latest develop so the CI builds properly?

**Comment by dwmoffatt** [comment]
Yeh I can rebase it. I will do it in the new year. I am busy until then.

**Comment by dwmoffatt** [comment]
@AndreMiras I have rebased it.

**Comment by AndreMiras** [comment]
Something went wrong with the rebase it seems. It should not show theses commits/diff :thinking:

**Comment by dwmoffatt** [comment]
Should I just create a new PR for it? This is what happened when I rebased the branch.

**Comment by AndreMiras** [comment]
No you don't need to make a new PR.
I've tried on my remote and it worked OK:
https://github.com/kivy/python-for-android/compare/develop...AndreMiras:Added-Ability-To-Change-Input-Type-Android?expand=1
All I did was:
```sh
git remote add dwmoffatt git@github.com:dwmoffatt/python-for-android.git
git fetch --all --prune
git rebase upstream/develop # upstream is git@github.com:kivy/python-for-android.git obviously
git push origin Added-Ability-To-Change-Input-Type-Android # you would require the `--force` flag for the overwrite
```
Maybe ping me on Discord so we can try to go through this together

**Comment by dwmoffatt** [comment]
@AndreMiras it was easier for me to spin a new PR so did that this morning. It's #2405

**Pull request closed without merging**
