### PR TITLE
recipes: add new `grpcio` recipe

### LINKED ISSUE #2498: gRPC Recipe Error
Hi everyone,

I continue the issue described here: https://github.com/kivy/python-for-android/issues/1052 . The idea is to create a gRPC recipe for p4a.

I tried to fork the existing recipe, https://github.com/hpsaturn/p4a_grpc_recipe/blob/master/__init__.py. The recipe there was built inside the docker container, and all the dependencies were also installed separately.
In my fork https://github.com/Splato/p4a_grpc_recipe/edit/master/__init__.py I install all dependencies as 'modules' (code lines 129-133) except for the openssl package (grpc installs BoringSSL that fails in p4a). However, I get the following error after compiling 60% of the recipe:

```
[ 60%] Linking CXX shared library libgrpc_plugin_support.so
CMakeFiles/grpc_plugin_support.dir/src/compiler/python_generator.cc.o: In function `PythonGrpcGenerator':
~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/grpcio/arm64-v8a__ndk_target_21/grpcio/grpc/src/compiler/python_generator.cc:829: undefined reference to `google::protobuf::compiler::CodeGenerator::~CodeGenerator()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/grpc_plugin_support.dir/build.make:175: libgrpc_plugin_support.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:894: CMakeFiles/grpc_plugin_support.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Then I also tried to include protobuf as dependencies in the grpc recipe (the recipe protobuf_cpp https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/protobuf_cpp/__init__.py). Then I changed the protobuf to 'package' (129) and the path to libraries and executables in cmake (lines 112-115). However, then I got another error:
```
-- Looking for __system_property_get - found
CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:469 (file):
  file STRINGS file "/opt/install/include/google/protobuf/stubs/common.h"
  cannot be read.
Call Stack (most recent call first):
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:261 (include)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:475 (math):
  math cannot parse the expression: " / 1000000": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:261 (include)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:476 (math):
  math cannot parse the expression: " / 1000 % 1000": syntax error,
  unexpected exp_DIVIDE (2).
Call Stack (most recent call first):
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:261 (include)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:477 (math):
  math cannot parse the expression: " % 1000": syntax error, unexpected
  exp_MOD (2).
Call Stack (most recent call first):
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:261 (include)


-- Found Protobuf: /opt/install/lib/libprotobuf.a (found version "ERROR.ERROR.ERROR") 
-- Found OpenSSL: ~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/openssl/arm64-v8a__ndk_target_21/openssl1.1/libcrypto.so (found version "1.1.1k")  
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Renaming
--     ~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/grpcio/arm64-v8a__ndk_target_21/grpcio/grpc/third_party/zlib/zconf.h
-- to 'zconf.h.included' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
-- Configuring incomplete, errors occurred!
See also "~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/grpcio/arm64-v8a__ndk_target_21/grpcio/grpc/build/CMakeFiles/CMakeOutput.log".
See also "~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/grpcio/arm64-v8a__ndk_target_21/grpcio/grpc/build/CMakeFiles/CMakeError.log".
```
So I guess at this point, I need some help with configuring the protobuf installation. Thanks.

### PR DESCRIPTION
**Pull request by kengoon**
fix #2498

### CODE REVIEW

**Comment by T-Dynamos** [comment]
@kengoon Hi!

Can we make this compatible with `PyProjectRecipe`?

**Comment by kengoon** [comment]
@T-Dynamos how? is there a guide line? Grpcio does not make use of poetry

**Comment by misl6** [comment]
Hi @kengoon,

Our CI/CD pipeline noticed something that should not happen while building the `grpcio` recipe.
BTW, better to ensure every new recipe build is isolated and performed via `PyProjectRecipe` as @T-Dynamos suggested.

Ping me when ready for the final review and a merge.

**Comment by kengoon** [comment]
@misl6 PyPtojectReciepe requires pyproject.toml file right? I'm now asking how do I go about using that, the guidelines. Because grpcio does not use use pyproject.toml file

https://github.com/kivy/python-for-android/blob/5dc17e16217620daf76d58ac6d20e4f9a9d4ff8b/pythonforandroid/recipe.py#L1175

**Comment by misl6** [comment]
> @misl6 PyPtojectReciepe requires pyproject.toml file right? I'm now asking how do I go about using that, the guidelines. Because grpcio does not use use pyproject.toml file

Ouch, I see they have an issue opened for that.

@T-Dynamos , anything we can do on our side to have an isolated build without `pyproject.toml` ?

**Comment by T-Dynamos** [comment]
`PyProjectRecipe`  support both build systems.

```
* Creating isolated environment: venv+pip...
ERROR Source /home/sompath does not appear to be a Python project: no pyproject.toml or setup.py
```




Also I have built this recipe locally with `PyProjectRecipe` and it works.

**Comment by kengoon** [comment]
@T-Dynamos and @misl6  Alright I will see to it. @T-Dynamos can you share a copy of the changes you made to make it work with PyProject

**Comment by T-Dynamos** [comment]
@kengoon 

Changes are in  GitHub review.

**Comment by kengoon** [comment]
@T-Dynamos I can't see any reviews here

**Comment by kengoon** [comment]
@T-Dynamos thanks for your help with the guide on migrating to PyProjectRecipe

**Comment by kengoon** [comment]
@misl6 a nice ping for you

**Comment by T-Dynamos** [comment]
@kengoon You forgot to include `use-ndk-zlib-and-openssl-recipe-include.patch`:

````python

    patches = ["comment-getserverbyport-r-args.patch", "remove-android-log-write.patch"]

**Comment by kengoon** [comment]
@T-Dynamos oh sh*t

**Comment by kengoon** [comment]
@misl6 ready for you

**Review by AndreMiras — APPROVED** [review]
LGTM, CI is mostly happy on the "Test updated recipes" except for macOS, but it's already better than the previous state of no recipe at all.
Thank you all for the efforts :muscle:

**Pull request merged**
