### PR TITLE
Added audiostream recipe

### PR DESCRIPTION
**Pull request by hottwaj**
I've included code to allow either sdl or sdl2 dependency.

However the library itself only links against SDL1 at the moment - the library needs to be changed to know when it is being linked against SDL2 (library names to link are slightly different)

### CODE REVIEW

**Comment by inclement** [comment]
Nice, thanks. Could you make the recipe actually fail (I guess print a message and throw an exception or just exit()) if it's built with sdl2, to make it clear to the user what the problem is? I think that would be the best way for now.

**Comment by hottwaj** [comment]
Sure - just added that.  Do you know of a way of passing an option to setup.pu (distutils) so that we can tell audiostream whether to do an SDL or SDL2 link?  If there is a mechanism for passing that info I can get the SDL2 route finished off.  Thanks!

**Comment by inclement** [comment]
Thanks, merged.

I'm not sure what's the best way to pass things to setup.py. One option is an environment variable (and to modify the setup.py to check it) - this is what e.g. kivy does. A cruder option is what I did with pyjnius, to add a patch that changes the behaviour, but this is less desirable.

**Comment by hottwaj** [comment]
OK thanks, an environment variable would pretty easy to set up.

I'll add that in when I get back to testing what I'm working on with the sdl2 bootstrap. 

Cheers!

**Pull request merged**
