### PR TITLE
restrict sh version

### PR DESCRIPTION
**Pull request by HyTurtle**
keep sh version under 2.0 as default behaviour was switched

### CODE REVIEW

**Comment by misl6** [comment]
Hi @HyTurtle !

Can you please explain why this is needed?

**Comment by HyTurtle** [comment]
https://github.com/amoffat/sh/blob/develop/MIGRATION.md#return-value-now-a-true-string

it now defaults to a string #2745 #2593 related

**Review by misl6 — APPROVED** [review]
Thank you for explaining!
Let's wait for the CI pipeline to complete, but LGTM.

I guess we should have an emergency release this weekend.

I will then open an issue to remind us that `sh.Command` usage should be migrated to be future-proof.

**Comment by HyTurtle** [comment]
Sounds like a plan.

Closes #2745

**Pull request merged**
