### PR TITLE
Fix master only merges

### PR DESCRIPTION
**Pull request by inclement**
Merge master into develop, to pull in the couple of PRs that have been made straight to master.

I know it's easy to miss, but PRs should go to develop. Not sure if we can protect master more, maybe non-core-devs can be blocked from making PRs to master.

### CODE REVIEW

**Comment by Fak3** [comment]
By the way, why the project needs separate develop branch? People are confused by that, as most of other projects use master branch to track the recent commits.

**Comment by inclement** [comment]
It doesn't "need" it, it's just a convenient workflow. We roughly follow a [git flow](https://nvie.com/posts/a-successful-git-branching-model/)-type model.

**Comment by Fak3** [comment]
I mean... What is exactly you find convenient in having develop branch instead of master?

**Comment by inclement** [comment]
We're making the choice that master represents the latest stable/released state (notionally it will always be production-ready), while develop represents the unstable development state. The names are fairly arbitrary, we're going with the original git-flow names as linked above.

**Comment by Fak3** [comment]
Hm, I thought that there are some practical reasons rather than historical

**Review by AndreMiras — APPROVED** [review]
LGTM thanks

**Comment by AndreMiras** [comment]
It is a practical reason @Fak3. You can read the post inclement shared above https://nvie.com/posts/a-successful-git-branching-model/
It basically explain why this is a convenient model

**Comment by Fak3** [comment]
> It is a practical reason @Fak3. You can read the post inclement shared above https://nvie.com/posts/a-successful-git-branching-model/
> It basically explain why this is a convenient model

What is "it"? I skimmed through this article and only left with impression that the naming is completely arbitrary. The kivy, plyer and dozens of other projects call the most recent branch as "master" instead of "develop". And use branch called "stable" or "vX.X" for latest stable code

**Comment by inclement** [comment]
Thanks @AndreMiras 

@Fak3 The naming is indeed arbitrary, except insofar as we selected this choice because we like it.

**Comment by xloem** [comment]
Thanks for merging this.

@Fak3 it sounds like you have personal experience that would give good reasons to do it another way.  The devs would need to know of these reasons to consider them.  It sounds like the lower the barriers to understanding the project are, the more small fixes can come in from other projects.  Changing things like this is usually something that would happen slowly with discussion, because many people have been working with it this way for a long time.

**Comment by Fak3** [comment]
The reason I asked is because this issue revealed to me that I was not the only one surprised by branch naming. If this becomes a significant enough annoyance for new contributors, then it may be worth to consider aligning the branch naming with kivy and most other projects. Another related issue is that git, github and many other projects are changing the "master" to "main", which is covered here: https://github.com/github/renaming. So if the p4a project going to align the naming with the rest of the world, then i would suggest to use "main" for the most recent stuff and "stable" for latest stable release.

**Comment by AndreMiras** [comment]
Thanks for explaining.
Using main and stable just feel as arbitrary to me. Both are documented workflows from different sources and we decided to chose Git-flow so far on p4a.
Regarding pull requesting on the correct branch this is done automatically on the default branch (which is `develop`) when you open a pull request unless someone changes it. It has happened a couple of times, but I don't feel it's something to worry about

**Pull request merged**
