### PR TITLE
Added sympy recipe

### PR DESCRIPTION
**Pull request by inclement**

### CODE REVIEW

**Comment by inclement** [comment]
I made this recipe ages ago, but I think I found a better way to fix the unicode thing, looking into it.

**Comment by AndreMiras** [comment]
Looking good to me, I've just added a minor comment

**Comment by AndreMiras** [comment]
Looks like this is not compiling, Travis fails with:
```
Please install the mpmath package with a version >= 0.19
```

**Comment by Ohadforman** [comment]
How can I add Please install the mpmath package with a version >= 0.19 to ignore list?

**Pull request merged**
