### PR TITLE
Ndk 15

### PR DESCRIPTION
**Pull request by dotnetslash**
Android NDK introduced optional unified headers in version 14. In 15, they are no longer optional. This request corrects flags as specifies an https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md

The changes broke the libffi and python2 in different ways. Fixes are included.

I suspect there's going to be impact on other recipes as well. Is there a test mechanism to test all available recipes?

### CODE REVIEW

**Comment by inclement** [comment]
Thanks a lot for this. It looks good, but I'll delay merging it for a few days while we prepare a release (aiming for this Saturday). After that there should be no delay.

**Comment by dotnetslash** [comment]
Cool. If anybody asked me now, I'd say hold off on updating your NDK. I'm just playing to learn kivy so I figured I'd be a good guinea pig.

**Comment by inclement** [comment]
I was able to get this working, but it required quite a few changes on top of this. Was this PR enough for you to build a Kivy app, without further modification?

**Comment by inclement** [comment]
I've made a new PR including these commits plus a few extra fixes, at https://github.com/kivy/python-for-android/pull/1103 . With these, everything seems to work great for me, although I'm still checking a couple of things. Assuming no surprises, I'll close this PR and merge from my branch shortly.

Thanks a lot for the contribution!

**Comment by inclement** [comment]
I think #1103 is all working, so I'm closing this so that it can be merged that way instead.

**Comment by dotnetslash** [comment]
Cool, thanks. The only kivy bit I've used so far is just an app to give me a python shell on a network port so you probably covered more area than I did.

**Pull request closed without merging**
