### PR TITLE
[Core] Get the latest version of requests.

### PR DESCRIPTION
**Pull request by hobbestigrou**

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
This might even work if it doesn't require a newer interpreter as it's just a standalone recipe. Try it without modifying the interpreter recipe and see if it works correctly on your device.

**Comment by inclement** [comment]
This is probably fine, but I'll leave merging it until after the release unless someone can confirm it.

**Comment by adrienbrunet** [comment]
I do confirm it works for me and our app  :)

**Comment by inclement** [comment]
Thanks!

**Pull request merged**
