### PR TITLE
ffmpeg and ffpyplayer improvements

### PR DESCRIPTION
**Pull request by rnixx**
Update versions of ffmpeg and ffpyplayer recipes.
Do not enable building of GPL components if not necessary.
Add support for x86 build in ffmpeg recipe

### CODE REVIEW

**Comment by rnixx** [comment]
Relates to https://github.com/matham/ffpyplayer/pull/100

**Comment by germn** [comment]
Hello! 
I was also updating these recipes recently for my project. Some dependencies for ffmpeg codecs can be updated as well. 
Maybe you could pick them for this PR from this commit?
https://github.com/germn/python-for-android/commit/d200d7f22676aa945bba8fbe20da795f559eeae9

I've tried and it seems to compile ok, also successfully checked on couple of videos.

**Comment by rnixx** [comment]
@germn can you create a dedicated PR for updating shine and x264 recipes please?

**Comment by rnixx** [comment]
@AndreMiras @inclement @matham 

Are there any objections left on this PR? would be great if it can be merged, thanks.

**Review by AndreMiras — APPROVED** [review]
LGTM, thanks for the reminder @rnixx

**Pull request merged**
