### PR TITLE
Fix ImportError bug: cannot locate symbol "modf"

### PR DESCRIPTION
**Pull request by Neizvestnyj**
Fix this bug `ImportError: dlopen failed: cannot locate symbol "modf"`
https://github.com/kivy/buildozer/issues/1020

### CODE REVIEW

**Comment by inclement** [comment]
Seems reasonable, thanks, but I think it should ideally be in LDFLAGS.

**Comment by Neizvestnyj** [comment]
> Seems reasonable, thanks, but I think it should ideally be in LDFLAGS.

do you mean so?  `env ['LDFLAGS'] + = f ' -lm'`

**Comment by inclement** [comment]
Yes, but no need to make this one a format string, skip the f.

That said, looking at the recipe it looks like it uses `env['LIBS']` for this a few lines above. Could you check adding -lm in that line works?

**Comment by Neizvestnyj** [comment]
> Yes, but no need to make this one a format string, skip the f.
> 
> That said, looking at the recipe it looks like it uses `env['LIBS']` for this a few lines above. Could you check adding -lm in that line works?

Hmm and really, it should work, should I build a package using this recipe and then create a new pul request?

**Comment by tshirtman** [comment]
you could update this pull request instead of creating a new one, but aside that, yes.

**Comment by Neizvestnyj** [comment]
@tshirtman @inclement I did a test build, everything works

**Review by inclement — APPROVED** [review]
Nice, thanks.

**Pull request merged**
