### PR TITLE
Make presplash image fit the screen

### PR DESCRIPTION
**Pull request by Mystic-Mirage**
I made my presplash image to look good on all my devices with different screen resolutions.
Tested image sizes: 416x530, 256x256, 512x512, 1024x1024.
Tested screen resolutions (both -- portrait and landscape): 320x480, 480x800.

I am not math expert so more testing needed with different image sizes and screen resolutions. May be I just lucky. :)

### CODE REVIEW

**Comment by tito** [comment]
This is an interesting patch, however, it need to be configurable. Some splashscreen are not meant to be fitted. I'll let this PR open until somebody add an environmnent configuration that can be used to select the behavior.

I suggest:

ANDROID_SPLASHSCREEN=fit
ANDROID_SPLASHSCREEN=default

**Comment by j-santander** [comment]
@tito I can try my hand at adding those configuration options, but .... could you explain how the environment configuration works? is there somewhere I could read the details? or other configuration item that is currently handled in the same way?

I understand this would be an option in the build.py + some entry in the buildozer configuration file.
... and then that somehow gets added to the package and read from the Java/JNI code?

**Comment by j-santander** [comment]
Ok, I did it based on metadata, see pull request #408

**Comment by inclement** [comment]
Closing in favour of #408

**Pull request closed without merging**
