### PR TITLE
Fixes for NDK 15+

### PR DESCRIPTION
**Pull request by inclement**
This includes the main changes of @dotnetslash from #1095, plus some further fixes that I needed to get builds working.

~~Not for merging yet, still checking at least one thing.~~

### CODE REVIEW

**Comment by inclement** [comment]
This seems ready for merging to me, but testing would be appreciated. I've tried with the NDK r11c, r15c, and current CrystaX NDK.

**Comment by inclement** [comment]
It looks like this breaks sqlite3, the same way as described at https://github.com/android-ndk/ndk/issues/332 . Looking into it.

**Comment by inclement** [comment]
I think I'll also test this with NDK 16 (currently beta1 is available) before merging, as this removes the old platform headers. That should expose any issues with still using the old headers.

**Comment by inclement** [comment]
Everything seems to be working now, including with the NDK 16 beta1. I've run quite a few tests using NDK r11c, r15c, r16-beta1 and crystax, and they all seem to work, so let's go ahead and merge.

**Comment by astha-garg123** [comment]
How Adding -D_FILE_OFFSET_BITS=32 solves the issue ?

**Comment by inclement** [comment]
@astha-garg123 I found information about this at https://github.com/android-ndk/ndk/issues/332.

**Pull request merged**
