### PR TITLE
fix travis

### PR DESCRIPTION
**Pull request by obfusk**

### CODE REVIEW

**Comment by obfusk** [comment]
Ironically, one of the builds timed out downloading sqlite3. Seems to be fine otherwise.

**Comment by obfusk** [comment]
>  Could you simply remove the debugging code (ls and which).

I left it in intentionally so it would be easier to fix if the version changes again. But I can remove it of course.

**Comment by AndreMiras** [comment]
Yes I'd rather remove it indeed

**Comment by obfusk** [comment]
Removed.

**Comment by AndreMiras** [comment]
Re the macOS build, we may want to create a tech debt task and disable only the macOS build until this is fixed

**Pull request merged**
