### PR TITLE
modifications for ndk >= r22

### LINKED ISSUE #2391: p4a is not compatible with ndk >= 22
From the [changelog of ndk 22](https://github.com/android/ndk/wiki/Changelog-r22):

* The deprecated `<NDK>/platforms` and `<NDK>/sysroot` directories have been
  removed. These directories were merged and relocated into the toolchain during
  r19. The location of these contents should not be relevant to anyone,
  including build systems, since the toolchain handles them implicitly. If you
  are using a build system that hasn't adapted to the changes introduced in NDK
  r19, file a bug with your build system maintainer. See the [Build System
  Maintainers Guide] for information on using the NDK in your own build system.

### PR DESCRIPTION
**Pull request by obfusk**
* ndk >= r22 no longer supports
  - {ndk_dir}/platform
  - {ndk_dir}/sysroot
* add & use
  - ctx.ndk_standalone
  - ctx.ndk_sysroot
  - ctx.ndk_lib_dir
  - ctx.ndk_include_dir
* patch openssl
* add FIXMEs to some recipes
  - nothing should have changed for ndk < r22
  - modifications and/or testing may be needed for ndk >= r22
* CI: mark some packages as broken

---

Fixes #2391

* "Works for me" :sweat_smile:
* Needs a review & probably some tests :)

### CODE REVIEW

**Comment by obfusk** [comment]
Oddly, travis fails with

```
[INFO]:    Downloading matplotlib from https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip

Download failed: HTTP Error 403: Forbidden; retrying in 1 second(s)...Download failed: HTTP Error 403: Forbidden; retrying in 2 second(s)...Download failed: HTTP Error 403: Forbidden; retrying in 4 second(s)...Download failed: HTTP Error 403: Forbidden; retrying in 8 second(s)...error: HTTP Error 403: Forbidden
```

**Comment by obfusk** [comment]
It "works for me" :sweat_smile: and I don't think these modifications would impact anyone not using ndk >= r22 (which doesn't work without these changes anyway), so I think this can be merged (assuming CI agrees with me).

Adding a CI run w/ ndk r22 would be nice though.

**Comment by obfusk** [comment]
CI was happy, so I rebased & squashed.

**Comment by obfusk** [comment]
I'd appreciate some feedback on this (if someone has the time) :)

**Comment by misl6** [comment]
Can you confirm that with latest `develop` branch this PR is now un-needed? (At least in part)

**Comment by misl6** [comment]
NDK 23b is now the default supported version, I'm closing this PR as is now outdated.

Maybe you would like to try the latest changes on `develop`?

Thank you for taking care of `python-for-android`!

**Pull request closed without merging**
