### PR TITLE
Split toolchain.py into separate modules

### PR DESCRIPTION
**Pull request by inclement**
This is a WIP, do not merge yet!

Opinions welcome, I'm not certain about the best way to make some of the splitting choices.

### CODE REVIEW

**Comment by inclement** [comment]
@kived I've split it up as seemed sensible - toolchain.py remains the entry point, build.py contains most of the building stuff, and mostly each of the other class types is split up into its own module. Does it look okay to you?

(A few things remain to be done, like making each recipe import from the right submodule rather than via toolchain)

**Comment by kived** [comment]
Looks good to me! :+1:

**Comment by inclement** [comment]
Great. I noticed a couple of small bugs today, but I'll fix them and merge later tonight.

**Comment by kived** [comment]
I fixed a bug with imports in the pygame recipe by importing them in toolchain.py (debug and ensure_dir).

**Comment by inclement** [comment]
Thanks, I don't know how I missed that previous PR. Looks good now though so I'll merge.

**Pull request merged**
