### PR TITLE
Fix setup.py install breaking due to unicode characters in README.md on Python 3

### PR DESCRIPTION
**Pull request by JonasT**
Fix setup.py install breaking due to unicode characters in README.md on Python 3

### CODE REVIEW

**Comment by AndreMiras** [comment]
Thanks for giving it a try!
But I think the fix actually is https://github.com/kivy/python-for-android/pull/1666 right?
Have you tried running `tox` on your changes locally?

**Comment by JonasT** [comment]
@AndreMiras the fix for what? This fixes `setup.py` blowing up if unicode characters are in `README.md`, which they are right now

**Comment by JonasT** [comment]
Ok, fix works for me (tested both Python 3 and Python 2 install). Since I forgot to post the backtrace and this came up in chat, this is what it fixes:

```
Collecting https://github.com/kivy/python-for-android/archive/master.zip
  Downloading https://github.com/kivy/python-for-android/archive/master.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-gpvwn6h5/setup.py", line 56, in <module>
        long_description = fileh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 5032: ordinal not in range(128)
```

**Comment by AndreMiras** [comment]
Thanks for clarifying and thanks for simplifying the initial PR

**Pull request merged**
