### PR TITLE
Fix building openssl for python3crystax

### PR DESCRIPTION
**Pull request by agilewalker**
Fix based on the work of @emillynge https://github.com/kivy/python-for-android/pull/707

### CODE REVIEW

**Comment by emillynge** [comment]
Thanks for taking over :)

**Comment by agilewalker** [comment]
Glad to help :)

**Comment by inclement** [comment]
Thanks for fixing it up. It looks like this cuts out some of the changes to the recipe that have happened since the original PR, such as the download of the python3.6 crystax. Also, does this openssl method link properly with other recipes that try to use it?

**Comment by agilewalker** [comment]
There is no extensive testing has been done other than getting a working _ssl.so, but changes to openssl recipe should be minimal. This fix is initially made in limited success only intended for https://github.com/fyookball/electrum/pull/331. New to the p4a codebase, I'm out of depth for knowing how to add back Python3.6 change properly.

**Comment by agilewalker** [comment]
After more research, it's nice to find out @inclement has already done most of the 3.6 work already! https://github.com/inclement/crystax_python_builds/
No more prebulit but more archs should work?

**Comment by agilewalker** [comment]
Squash all changes into a single commit.

**Comment by AndreMiras** [comment]
I confirm that this pull request solves it for me to, the error was:
```
04-04 23:32:48.495 20544 20615 I python  :    File "/data/user/0/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/requests/adapters.py", line 506, in send
04-04 23:32:48.497 20544 20615 I python  :      raise SSLError(e, request=request)
04-04 23:32:48.497 20544 20615 I python  :  requests.exceptions.SSLError: HTTPSConnectionPool(host='ropsten.infura.io', port=443): Max retries exceeded with url: / (Caused by SSLError("Can't connect to HT
TPS URL because the SSL module is not available.",))
```
@agilewalker and @inclement that would be nice to have it integrated now that you've done the hardest part. Do you want me to rebase and continue?

**Comment by bauerj** [comment]
Hey @AndreMiras, this was superseded by #1217.

**Comment by inclement** [comment]
@AndreMiras I'm mildly disappointed to lose the prebuilt python3crystax functionality, but I guess I should just get over that.

I also don't like the way the build order is passed around, using floats. How do others feel about that?
 
Other than that, rebasing it would be great if it needs it, other than that I should just get around to testing it.

**Comment by AndreMiras** [comment]
Thanks @inclement 
> @AndreMiras I'm mildly disappointed to lose the prebuilt python3crystax functionality, but I guess I should just get over that.
Yes it's a shame, but perhaps we should just create another "technical debt" issue for this case.

> I also don't like the way the build order is passed around, using floats. How do others feel about that?
Yes I didn't deep dive into it, but a quick look does give headaches indeed :face_with_head_bandage: 

> Other than that, rebasing it would be great if it needs it, other than that I should just get around to testing it.
Yes I would say, let's move on, test it and merge it for now since it does bring an important feature. And we can take another look to refactor it once #625 is ready :grimacing: 

@bauerj yes this #1217 one is confusing me :thinking:

**Comment by bauerj** [comment]
How is this related to #625?

**Comment by AndreMiras** [comment]
Because it would make it easier to see if non functional changes do not break anything. At the moment it's very cumbersome to see if a recipes update provides something new without breaking something else.

**Comment by bauerj** [comment]
Well, it wouldn't be able to test whether the generated SSL module actually works, would it?

**Comment by AndreMiras** [comment]
Why not? We could go from something simple (verifying lib deps with ldd/readelf) to something more advanced, running some unit tests in an Android VM. That would be already quite advanced of course, but I do think it's possible.

**Comment by JonasT** [comment]
Just as a reminder for people dropping by: **look here https://github.com/JonasT/python-for-android/tree/tlsfix for a continuously updated TLS-enabling patch** for python 3 crystax. (I rebase it every few days onto latest python-for-android master!) It's not my work at all, I just try to keep it working on the latest changes.

I am in no way suggesting it should be merged since I also believe it to be a highly intermediate solution until non-crystax py3 is ready, but until the day that happens, I encourage anyone needing TLS to give it a try, and I hope this helps some folks out who drop by here searching for working TLS support

**Comment by JonasT** [comment]
@AndreMiras should we close this maybe? I don't see it ever being merged the way things are heading now with crystax on the way out of the door (mainly since the open pull requests are starting to pile up a little)

@agilewalker thanks a lot for looking into this btw, it has lived on for a while as `tlsfix` and saved many people a lot of trouble! but we might finally be heading somewhere where we no longer need it

**Comment by AndreMiras** [comment]
Also it's superseded by #1217

**Pull request closed without merging**
