### PR TITLE
Fixed keyboard issues for old_toolchain.

### PR DESCRIPTION
**Pull request by rafalo1333**
#483 by SapienTech for old_toolchain.

### CODE REVIEW

**Comment by inclement** [comment]
The deleted comment is mildly concerning, but presumably you've tested this and it worked? Maybe the new toolchain had some intermediate changes.

**Comment by akshayaurora** [comment]
This has nothing to do with #483 which is merged,  the comment is there to avoid this specifically,  this will lead to a crash when resuming the app we specifically added the comment in there for this reason.

**Comment by rafalo1333** [comment]
@akshayaurora I have tested it and I havent Got any crash, after resuming the app too. For me everything is working. 

But if you have a better solution everyone will be glad to see it ;)

**Comment by akshayaurora** [comment]
There is nothing to solve here,  #483 is already merged,  this just duplicates code, we already have the listener.

**Comment by rafalo1333** [comment]
It is merged in master, but until master will be officially out programmers need to use buildozer with the old_toolchain. Closing it you're leaving Kivy with TextInputs UNUSABLE on Android. 

If #483 was successfully merged, there should be a way to solve this problem also for old toolchain.

Closing this PR wont close the issue. And if youre so sure about "there is nothing to solve here" just look at #544, damn.

**Comment by akshayaurora** [comment]
@rafalo1333 #483 works for new toolchain however same code will not work for old_toolchain, 

old_toolchain implements the same code in SDLSurfaceview as outlined by the comment you removed https://github.com/kivy/python-for-android/blob/old_toolchain/src/src/org/renpy/android/SDLSurfaceView.java#L1210

this is where you want to include the change, not add another listener. There is a difference in the old_toolchain and the new one that's why the code will not work as is.

**Comment by akshayaurora** [comment]
original issue closed by 11db161

**Pull request closed without merging**
