### PR TITLE
Release 2020.04.29

### PR DESCRIPTION
**Pull request by AndreMiras**
- [x] Check that the [build is passing](https://travis-ci.org/kivy/python-for-android)
- [x] Run the tests locally via `tox` ([tox.log](https://github.com/kivy/python-for-android/files/4595032/tox.log)): this performs some long-running tests that are skipped on Travis.
- [ ] Build and run the [on_device_unit_tests](https://github.com/kivy/python-for-android/tree/master/testapps/on_device_unit_tests) app using buildozer. Check that they all pass.
- [ ] Build and run the following [testapps](https://github.com/kivy/python-for-android/tree/master/testapps) for arch `armeabi-v7a` and `arm64-v8a`:
  - `python3 setup_testapp_python3_sqlite_openssl.py apk`
    - [ ] `armeabi-v7a`
    - [ ] `arm64-v8a`
- [ ] Check that the version number is correct

### CODE REVIEW

**Comment by AndreMiras** [comment]
It's been only a month since the last release but already tons of commits.
This is releasing up to https://github.com/kivy/python-for-android/pull/2160 which is also fixing master

**Comment by inclement** [comment]
So this isn't releasing the newer stuff since the given date?

**Comment by AndreMiras** [comment]
I'm not sure I got the question :thinking:
This will release up to `#2160` which was merged the 29 of April. That's why I was thinking to tag this release a `v2020.04.29`

**Comment by AndreMiras** [comment]
I should have pull requested using the upstream branch. Will do that instead

**Pull request closed without merging**
