### PR TITLE
recipes: new `materialyoucolor` recipe

### PR DESCRIPTION
**Pull request by T-Dynamos**
Hoping for soon merge :)

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
Great!

**Comment by kengoon** [comment]
@T-Dynamos I'm getting this error at runtime
```python
Traceback (most recent call last):
01-20 07:58:44.920  3431  4181 I python  :    File "/mnt/c/Users/kengo/PycharmProjects/sjfirebase-app/.buildozer/android/app/main.py", line 14, in <module>
01-20 07:58:44.921  3431  4181 I python  :    File "/mnt/c/Users/kengo/PycharmProjects/sjfirebase-app/.buildozer/android/platform/build-arm64-v8a/build/python-installs/fireba
seapp/arm64-v8a/kivymd/app.py", line 67, in <module>
01-20 07:58:44.921  3431  4181 I python  :    File "/mnt/c/Users/kengo/PycharmProjects/sjfirebase-app/.buildozer/android/platform/build-arm64-v8a/build/python-installs/fireba
seapp/arm64-v8a/kivymd/theming.py", line 58, in <module>
01-20 07:58:44.921  3431  4181 I python  :    File "/mnt/c/Users/kengo/PycharmProjects/sjfirebase-app/.buildozer/android/platform/build-arm64-v8a/build/python-installs/fireba
seapp/arm64-v8a/materialyoucolor/quantize/__init__.py", line 1, in <module>
01-20 07:58:44.922  3431  4181 I python  :  ImportError: dlopen failed: cannot locate symbol "_ZTISt13runtime_error" referenced by "/data/data/org.sjfirbase.firebaseapp/files
/app/_python_bundle/site-packages/materialyoucolor/quantize/celebi.so"...
01-20 07:58:44.922  3431  4181 I python  : Python for android ended.
```

**Comment by T-Dynamos** [comment]
@kengoon Can you try this workaround https://github.com/kivy/python-for-android/issues/2675#issuecomment-1501578996.

**Comment by kengoon** [comment]
@T-Dynamos uninstalling cache fixed it. 👍

**Review by nastiliano — APPROVED** [review]

**Comment by AndreMiras** [comment]
LGTM, has someone else had the chance to test it? @nastiliano, @HeaTTheatR ?

**Comment by herbe13** [comment]
> LGTM, has someone else had the chance to test it? @nastiliano, @HeaTTheatR ?

I tested, it's good!

**Review by AndreMiras — APPROVED** [review]

**Comment by nastiliano** [comment]
For me too.
Thank you very much

**Pull request merged**
