### PR TITLE
Removed conflict with python3crystax for requests

### PR DESCRIPTION
**Pull request by VineethRaghavan**
Remove python2 dependencies in requests recipe to remove conflict with python3crystax

### CODE REVIEW

**Comment by inclement** [comment]
It looks like this allows requests to be included (so the openssl dependency was apparently erroneous), but that it won't actually run on the device without openssl, which our python3 build doesn't yet include. Is this experience the same as yours?

**Comment by inclement** [comment]
(For reference): Would be fixed by https://github.com/kivy/python-for-android/issues/1072

**Comment by VineethRaghavan** [comment]
I didn't get an opportunity to try it out, so I don't know. But I'll believe what you say.

Regarding the openssl dependency, if requests does require openssl can I expect that dependency to be fixed by python for android 0.5?

**Comment by VineethRaghavan** [comment]
BTW, why hadn't you added openssl to the python 3 build considering the fact that it is a dependency of a library like requests?

**Comment by inclement** [comment]
I don't expect openssl for python3 to be added before the next release
(which should be quite soon), but it will be a priority afterwards.

**Comment by inclement** [comment]
> BTW, why hadn't you added openssl to the python 3 build considering the fact that it is a dependency of a library like requests?

Because I haven't had time to do everything I'd like to, and this is something that has lost out so far.

**Comment by VineethRaghavan** [comment]
Thanks for the reply. I'll be looking forward to the next release (hopefully with openssl support for python 3!).
I'll close this issue now.
Once again, thanks!

**Comment by inclement** [comment]
I'll leave this open, the fix seems good, it's just that the lack of openssl prevents the request import from actually working.

**Comment by AndreMiras** [comment]
I think [current version of requests recipe](https://github.com/kivy/python-for-android/blob/ccd5b59/pythonforandroid/recipes/requests/__init__.py) compiles just fine with python3crystax. I'm using it for a couple of projects.
Feel free to reopen otherwise.

**Pull request closed without merging**
