### PR TITLE
recipes: add a few recipes

### LINKED ISSUE #2600: [Recipe Request]:Panda3d,Ursina
Including this packages will replace unity3d and ue4

### LINKED ISSUE #2997: please add uvloop to recipes!
please add uvloop to recipes! uvloop is a fast, drop-in replacement of the built-in 'asyncio' event loop. This has greatly improved the performance of our project. We urgently need it.  please! 🙏🙏🙏
uvloop url: https://github.com/MagicStack/uvloop/tree/master

### LINKED ISSUE #3012: Add recipe `pyreqwest_impersonate`
### Versions

- Python: 3.10
- OS: Linux mint
- Kivy: 2.2.1
- Cython: 0.29.33
- OpenJDK: 17

### Description

I made the recipe according to the example:
```
from pythonforandroid.recipe import RustCompiledComponentsRecipe


class Pyreqwest_impersonateRecipe(RustCompiledComponentsRecipe):
    version = "v0.4.1"
    url = "https://github.com/deedy5/pyreqwest_impersonate/archive/refs/tags/{version}.tar.gz"
    use_maturin = True
    hostpython_prerequisites = ["typing_extensions"]
    site_packages_name = "pyreqwest_impersonate"


recipe = Pyreqwest_impersonateRecipe()
```

### buildozer.spec

```
# (str) The directory in which python-for-android should look for your own build recipes (if any)
p4a.local_recipes = /home/odinson/PycharmProjects/OSINT/src/python-for-android/recipes/
```

### Logs

```
File "/home/odinson/PycharmProjects/OSINT/src/python-for-android/recipes/pyreqwest_impersonate/__init__.py", line 1, in <module>
    from pythonforandroid.recipe import RustCompiledComponentsRecipe
ImportError: cannot import name 'RustCompiledComponentsRecipe' from 'pythonforandroid.recipe' (/home/odinson/PycharmProjects/OSINT/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py)

```

`buildozer clean`  I did too. I did everything as required according to the documentation.

### PR DESCRIPTION
**Pull request by T-Dynamos**
Closes #2997 , Closes #2600 , Closes #3012 

- [x] uvloop
- [x] pyreqwest_impersonate
- [x] panda3D
- [ ] polars

### CODE REVIEW

**Comment by T-Dynamos** [comment]
@AndreMiras Hi!

Can you please investigate why logs for ubuntu are of `140MB`?
Why `sh`'s logging level is auto set to debug?

**Comment by AndreMiras** [comment]
Ouch that's a lot of logs. I have been out of the loop for a long while. Is this a new issue? And can you reproduce in local?

**Comment by T-Dynamos** [comment]
Closing as we need to split recipes into PRs.

**Comment by AndreMiras** [comment]
I looked up into the sh logging level issue.
I think it was initially an old upstream sh issue. But it seems like our rebuild updated recipe CI job is running from an old p4a Docker image. I'll try to see if we fix the DockerHub image so it's always fresh and hopefully that would fix the logging issue and some more
Edit: this is how we ended up addressing it https://github.com/kivy/python-for-android/pull/3048

**Pull request closed without merging**
