### PR TITLE
Add remove_presplash

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
Remove SDL2 presplash function in `android` package.

ref #928

### CODE REVIEW

**Comment by inclement** [comment]
I wonder if it would be preferable to just put this in an `if BOOTSTRAP == 'sdl2'` block rather than using the catchall try/except - this would be more in line with how the android module is currently structured, and I think fits fine with its somewhat ad-hoc support for things.

**Comment by KeyWeeUsr** [comment]
So it's just a [casual Python](https://github.com/KeyWeeUsr/python-for-android/blob/2094aea9a3a7a01840eab6ee972b7004590b9e0a/pythonforandroid/recipes/android/src/android/_android.pyx#L5)? It really doesn't seem like that, C macro rather and even that probably not. I can't find the `config.pxi` where I should probably look for the thing.

I mean, I can check for `'sdl2'` but if I don't know if it really returns such thing with SDL2 on android, the code most likely won't be executed. Maybe it's just copied from the old code e.g. no `'sdl2'` will be returned, because there was pygame only. Or I'm just confused, hmmm...

**Comment by inclement** [comment]
I actually just guessed that 'sdl2' would work, you're right that we should understand it first.

**Comment by inclement** [comment]
Looks like the config files are all written by the android recipe, and BOOTSTRAP is indeed just the bootstrap name, so checking for `'sdl2'` should be fine.

**Comment by inclement** [comment]
👍

**Pull request merged**
